// src/pages/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRightIcon,
  MapPinIcon,
  UsersIcon,
  ZapIcon,
  ShieldCheckIcon,
  TrophyIcon,
  Gamepad2Icon,
  TerminalIcon,
  FlameIcon,
  CameraIcon,
  SparklesIcon,
  ClockIcon
} from 'lucide-react';
import { CountdownCard } from '../components/CountdownCard';
import { ScheduleTimeline } from '../components/ScheduleTimeline';
import {
  EVENTS,
  EVENT_STARTS_AT,
  REGISTRATION_CLOSES_AT,
  REGISTRATION_FEE
} from '../data/events';

const EVENT_ICONS: Record<string, typeof TrophyIcon> = {
  hackathon: TrophyIcon,
  '2d-games': Gamepad2Icon,
  ctf: TerminalIcon,
  egames: FlameIcon
};

const EVENT_COLOR_CLASSES: Record<string, { iconBg: string; iconColor: string; badgeColor: string }> = {
  hackathon: {
    iconBg: 'bg-sky-50',
    iconColor: 'text-[#0EA5E9]',
    badgeColor: 'border-[#0EA5E9]/40 text-[#0284C7]'
  },
  '2d-games': {
    iconBg: 'bg-blue-50',
    iconColor: 'text-[#2563EB]',
    badgeColor: 'border-[#2563EB]/40 text-[#2563EB]'
  },
  ctf: {
    iconBg: 'bg-slate-100',
    iconColor: 'text-[#0F172A]',
    badgeColor: 'border-[#64748B]/40 text-[#0F172A]'
  },
  egames: {
    iconBg: 'bg-sky-50',
    iconColor: 'text-[#0EA5E9]',
    badgeColor: 'border-[#0EA5E9]/40 text-[#0284C7]'
  }
};

export function Home() {
  return (
    <div className="space-y-20 py-4">
      {/* ───────────────────────────────────────────────────────────── */}
      {/* 1. HERO SECTION (CYBER BLUE & POLISHED SILVER LUXURY) */}
      {/* ───────────────────────────────────────────────────────────── */}
      <section className="relative grid gap-10 pt-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)] lg:items-center lg:gap-14">
        <div className="relative z-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#0EA5E9] bg-[#FFFFFF] px-4 py-1.5 text-xs font-mono font-bold uppercase tracking-widest text-[#0284C7] shadow-sm">
            <SparklesIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
            <span>Jaya Engineering College · National Level Tech Innovation Challenge</span>
          </div>

          <h1 className="mt-5 font-serif text-5xl font-black leading-[1.08] tracking-tight text-[#000000] sm:text-6xl lg:text-7xl">
            Inspire. Invent.
            <br />
            <span className="text-[#0EA5E9]">
              Impact.
            </span>
          </h1>

          <p className="mt-6 max-w-xl text-base leading-relaxed text-[#475569] sm:text-lg">
            Five premier national technical arenas, one prestigious campus, one defining day.
            RYVANTA '26 takes off on{' '}
            <span className="font-bold text-[#000000]">19 September 2026</span> at Jaya Engineering College — an entry fee of{' '}
            <span className="font-bold text-[#0EA5E9]">₹{REGISTRATION_FEE}</span> per person grants full access to compete and win prizes.
          </p>

          {/* Key Value Badges */}
          <div className="mt-6 flex flex-wrap gap-2.5 text-xs font-mono">
            <span className="rounded-xl border border-[#E2E8F0] bg-[#FFFFFF] px-3.5 py-2 text-[#000000] font-semibold flex items-center gap-2 shadow-sm">
              <TrophyIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
              {EVENTS.length} Technical Arenas
            </span>
            <span className="rounded-xl border border-[#E2E8F0] bg-[#FFFFFF] px-3.5 py-2 text-[#000000] font-semibold flex items-center gap-2 shadow-sm">
              <ZapIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
              ₹{REGISTRATION_FEE} Per Person Entry
            </span>
            <span className="rounded-xl border border-[#E2E8F0] bg-[#FFFFFF] px-3.5 py-2 text-[#000000] font-semibold flex items-center gap-2 shadow-sm">
              <ShieldCheckIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
              Instant Participation ID (TICH/TID/TIC/TIE)
            </span>
          </div>

          {/* Action CTAs */}
          <div className="mt-8 flex flex-wrap items-center gap-4">
            <Link
              to="/events"
              className="group inline-flex items-center gap-2 rounded-xl bg-[#0EA5E9] px-8 py-4 text-xs font-bold uppercase tracking-wider text-[#FFFFFF] shadow-luxury hover:bg-[#0284C7] hover:shadow-blue-glow transition-all duration-200 hover:scale-[1.02]"
            >
              <span>Register Your Team</span>
              <ArrowRightIcon className="h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 text-[#E0F2FE]" />
            </Link>

            <Link
              to="/support"
              className="inline-flex items-center gap-2 rounded-xl border border-[#CBD5E1] bg-[#FFFFFF] px-6 py-4 text-xs font-bold uppercase tracking-wider text-[#000000] transition-colors hover:border-[#0EA5E9] hover:bg-sky-50/40"
            >
              <span>Helpline &amp; Support</span>
            </Link>
          </div>
        </div>

        {/* Dual Live Countdowns (Exact 10-09-2026 & 19-09-2026) */}
        <div className="space-y-4">
          <CountdownCard
            label="Registration Closes In"
            target={REGISTRATION_CLOSES_AT}
            caption="Registration Deadline: 10 September 2026, 11:59 PM IST"
            completeLabel="Registration closed"
            emphasis
          />

          <CountdownCard
            label="Challenge Commences In"
            target={EVENT_STARTS_AT}
            caption="Reporting Time: 19 September 2026, 08:30 AM IST (All Main Events)"
            completeLabel="Live today"
          />
        </div>
      </section>

      {/* ───────────────────────────────────────────────────────────── */}
      {/* 2. EVENT SCHEDULE & TIMELINE COMPONENT */}
      {/* ───────────────────────────────────────────────────────────── */}
      <ScheduleTimeline />

      {/* ───────────────────────────────────────────────────────────── */}
      {/* 3. DIGITAL POSTER CARDS FOR THE 5 TECHNICAL EVENTS */}
      {/* ───────────────────────────────────────────────────────────── */}
      <section aria-labelledby="lineup-heading" className="space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 border-b border-[#E2E8F0] pb-4">
          <div>
            <span className="font-mono text-xs font-bold uppercase tracking-widest text-[#0EA5E9]">
              Jaya Engineering College Technical Arenas
            </span>
            <h2
              id="lineup-heading"
              className="mt-1 font-serif text-3xl font-bold tracking-tight text-[#000000] sm:text-4xl"
            >
              Official Event <span className="text-[#0EA5E9]">Lineup</span> &amp; Modules
            </h2>
          </div>
          <span className="rounded-xl border border-[#0EA5E9] bg-[#FFFFFF] px-4 py-1.5 text-xs font-mono font-bold uppercase tracking-widest text-[#000000] shadow-sm">
            {EVENTS.length} Flagship Events
          </span>
        </div>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {EVENTS.map((event) => {
            const Icon = EVENT_ICONS[event.id] || TrophyIcon;
            const colors = EVENT_COLOR_CLASSES[event.id] || EVENT_COLOR_CLASSES.hackathon;
            return (
              <Link
                key={event.id}
                to={`/events?event=${event.id}`}
                className="group relative flex flex-col justify-between overflow-hidden rounded-2xl border border-[#E2E8F0] bg-[#FFFFFF] p-7 transition-all duration-300 hover:-translate-y-1 hover:border-[#0EA5E9] hover:shadow-luxury-lg"
              >
                <div>
                  <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-3">
                    <span className="font-mono text-xs font-bold tracking-widest text-[#0EA5E9]">
                      CODE: TI{event.code}1001
                    </span>
                    <span className="rounded-md border border-[#E2E8F0] bg-[#F8FAFC] px-2.5 py-1 text-[10px] font-mono font-semibold text-[#475569]">
                      {event.minMembers === event.maxMembers
                        ? `${event.minMembers} Members`
                        : `${event.minMembers}–${event.maxMembers} Members`}
                    </span>
                  </div>

                  <div className="mt-4 flex items-center gap-3">
                    <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${colors.iconBg} border border-[#CBD5E1] ${colors.iconColor} group-hover:bg-[#000000] group-hover:text-[#FFFFFF] transition-colors`}>
                      <Icon className="h-5 w-5" />
                    </div>
                    <h3 className="font-serif text-xl font-bold text-[#000000] group-hover:text-[#0EA5E9] transition-colors">
                      {event.fullName}
                    </h3>
                  </div>

                  <p className="mt-3 text-xs text-[#475569] leading-relaxed">
                    {event.tagline}
                  </p>

                  {/* Event Badges / Format Specs */}
                  {event.scoringMatrix && (
                    <div className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-[#CBD5E1] bg-[#F8FAFC] px-2.5 py-1 text-[10px] font-mono font-bold text-[#2563EB]">
                      <span>6-Category Scoring Matrix (100 Marks)</span>
                    </div>
                  )}

                  {event.formatDetails && (
                    <div className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-[#0EA5E9]/40 bg-[#F8FAFC] px-2.5 py-1 text-[10px] font-mono font-bold text-[#0EA5E9]">
                      <span>2 Rounds · 2 Flags to Capture</span>
                    </div>
                  )}

                  {event.requiresDepartment && (
                    <div className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-[#0EA5E9]/40 bg-[#F8FAFC] px-2.5 py-1 text-[10px] font-mono font-bold text-[#0EA5E9]">
                      <span>Dynamic Department Selector (7 Depts)</span>
                    </div>
                  )}

                  {event.id === 'egames' && (
                    <div className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-[#0EA5E9]/40 bg-[#F8FAFC] px-2.5 py-1 text-[10px] font-mono font-bold text-[#0EA5E9]">
                      <span>4 Players Squad · Network Lab</span>
                    </div>
                  )}

                </div>

                <div className="mt-6 flex items-center justify-between border-t border-[#E2E8F0] pt-4 text-xs font-mono text-[#64748B]">
                  <span className="inline-flex items-center gap-1.5 text-[#334155] font-semibold">
                    <MapPinIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                    {event.venue}
                  </span>

                  <span className="inline-flex items-center gap-1 font-bold text-[#000000] group-hover:translate-x-1 group-hover:text-[#0EA5E9] transition-all">
                    <span>Register</span>
                    <ArrowRightIcon className="h-3.5 w-3.5" />
                  </span>
                </div>
              </Link>
            );
          })}
        </div>
      </section>
    </div>
  );
}

// src/views/Home.vue
<script setup>
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import {
  ArrowRightIcon,
  MapPinIcon,
  ZapIcon,
  ShieldCheckIcon,
  TrophyIcon,
  Gamepad2Icon,
  TerminalIcon,
  FlameIcon,
  SparklesIcon
} from 'lucide-vue-next'
import CountdownCard from '../components/CountdownCard.vue'
import ScheduleTimeline from '../components/ScheduleTimeline.vue'
import {
  EVENTS,
  EVENT_STARTS_AT,
  REGISTRATION_CLOSES_AT
} from '../data/events'

const REGISTRATION_FEE = 100

function scrollToEvents() {
  const el = document.getElementById('events-lineup')
  if (el) el.scrollIntoView({ behavior: 'smooth' })
}

const getIconForEvent = (id) => {
  const icons = {
    hackathon: TrophyIcon,
    games2d: Gamepad2Icon,
    ctf: TerminalIcon,
  }
  return icons[id] || TrophyIcon
}

const getEventThemeClass = (id) => {
  const classes = {
    hackathon: 'theme-hackathon',
    games2d: 'theme-games',
    ctf: 'theme-ctf',
  }
  return classes[id] || 'theme-hackathon'
}
</script>

<template>
  <div class="home-container">
    <!-- HERO SECTION -->
    <section class="hero-section">
      <div class="hero-content">
        <div class="hero-badge">
          <span>Tech Innovation Challenge</span>
        </div>

        <h1 class="hero-title">
          RYVANTA
          <span class="text-brand">'26</span>
        </h1>

        <p class="hero-desc">
          RYVANTA '26 takes off on <span class="text-bold">19 September 2026</span> at Jaya Engineering College — an entry fee of <span class="text-brand-bold">₹{{ REGISTRATION_FEE }}</span> per person grants full access to compete and win prizes.
        </p>

        <!-- Key Value Badges -->
        <div class="key-values-container">
          <span class="key-value-item">
            <TrophyIcon class="key-value-icon" />
            {{ EVENTS.length }} Technical Arenas
          </span>
          <span class="key-value-item">
            <ZapIcon class="key-value-icon" />
            ₹{{ REGISTRATION_FEE }} Per Person Entry
          </span>
        </div>

        <!-- Action CTAs -->
        <div class="hero-actions">
          <button @click="scrollToEvents" class="btn-primary hero-btn">
            <span>Register Your Team</span>
            <ArrowRightIcon class="btn-icon-right" />
          </button>

          <RouterLink to="/support" class="btn-secondary hero-btn">
            <span>Helpline &amp; Support</span>
          </RouterLink>
        </div>
      </div>

      <!-- Countdowns -->
      <div class="countdowns-container">
        <CountdownCard
          label="Registration Closes In"
          :target="REGISTRATION_CLOSES_AT"
          caption="Registration Deadline: 10 September 2026, 11:59 PM IST"
          completeLabel="Registration closed"
          :emphasis="true"
        />

        <CountdownCard
          label="Challenge Commences In"
          :target="EVENT_STARTS_AT"
          caption="Reporting Time: 19 September 2026, 08:30 AM IST (All Main Events)"
          completeLabel="Live today"
        />
      </div>
    </section>

    <!-- EVENT SCHEDULE COMPONENT -->
    <ScheduleTimeline />

    <!-- DIGITAL POSTER CARDS -->
    <section id="events-lineup" class="lineup-section" aria-labelledby="lineup-heading">
      <div class="lineup-header">
        <div>
          <span class="lineup-subtitle">
            Technical Arenas
          </span>
          <h2 id="lineup-heading" class="lineup-title">
            Event <span class="text-brand">Lineup</span>
          </h2>
        </div>
        <span class="lineup-count-badge">
          {{ EVENTS.length }} Flagship Events
        </span>
      </div>

      <div class="events-grid">
        <RouterLink
          v-for="event in EVENTS"
          :key="event.id"
          :to="{ name: 'register', query: { event: event.id } }"
          class="event-card group"
        >
          <div>
            <div class="event-card-title-group">
              <div class="event-icon-wrapper" :class="getEventThemeClass(event.id)">
                <component :is="getIconForEvent(event.id)" class="event-icon" />
              </div>
              <h3 class="event-title">
                {{ event.fullName }}
              </h3>
            </div>

            <p class="event-desc">
              {{ event.tagline }}
            </p>
          </div>
              <span class="event-team-size">
                {{ `${event.memberCounts[0]}/${event.memberCounts[1]} Members` }}
              </span>

          <div class="event-card-footer">
            <span class="event-venue">
              <MapPinIcon class="event-venue-icon" />
              {{ event.venue }}
            </span>

            <span class="event-action">
              <span>Register</span>
              <ArrowRightIcon class="event-action-icon" />
            </span>
          </div>
        </RouterLink>
      </div>
    </section>
  </div>
</template>

<style scoped>
.home-container {
  display: flex;
  flex-direction: column;
  gap: 5rem;
  padding: 1rem 0;
}

/* HERO SECTION */
.hero-section {
  position: relative;
  display: grid;
  gap: 2.5rem;
  padding-top: 1.5rem;
}

@media (min-width: 1024px) {
  .hero-section {
    grid-template-columns: minmax(0, 1.3fr) minmax(0, 1fr);
    align-items: center;
    gap: 3.5rem;
  }
}

.hero-content {
  position: relative;
  z-index: 10;
}

.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  border-radius: var(--radius-full);
  border: 1px solid var(--brand-blue);
  background-color: var(--bg-primary);
  padding: 0.375rem 1rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--brand-blue-hover);
  box-shadow: var(--shadow-sm);
}

.hero-badge-icon {
  width: 0.875rem;
  height: 0.875rem;
  color: var(--brand-blue);
}

.hero-title {
  margin-top: 1.25rem;
  font-family: var(--font-serif, var(--font-sans));
  font-size: 3rem;
  font-weight: 900;
  line-height: 1.08;
  letter-spacing: -0.025em;
  color: var(--text-primary);
}

@media (min-width: 640px) { .hero-title { font-size: 3.75rem; } }
@media (min-width: 1024px) { .hero-title { font-size: 4.5rem; } }

.text-brand { color: var(--brand-blue); }
.text-bold { font-weight: 700; color: var(--text-primary); }
.text-brand-bold { font-weight: 700; color: var(--brand-blue); }

.hero-desc {
  margin-top: 1.5rem;
  max-width: 36rem;
  font-size: 1rem;
  line-height: 1.6;
  color: var(--text-secondary);
}

@media (min-width: 640px) { .hero-desc { font-size: 1.125rem; } }

.key-values-container {
  margin-top: 1.5rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.625rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
}

.key-value-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border-light);
  background-color: var(--bg-primary);
  padding: 0.5rem 0.875rem;
  font-weight: 600;
  color: var(--text-primary);
  box-shadow: var(--shadow-sm);
}

.key-value-icon {
  width: 0.875rem;
  height: 0.875rem;
  color: var(--brand-blue);
}

.hero-actions {
  margin-top: 2rem;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 1rem;
}

.btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  border-radius: var(--radius-xl);
  background-color: var(--brand-blue);
  padding: 1rem 2rem;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #FFFFFF;
  box-shadow: var(--shadow-luxury);
  transition: all 0.2s ease;
}
.btn-primary:hover {
  background-color: var(--brand-blue-hover);
  transform: scale(1.02);
}

.btn-secondary {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border-dark);
  background-color: var(--bg-primary);
  padding: 1rem 1.5rem;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-primary);
  transition: all 0.2s ease;
}
.btn-secondary:hover {
  border-color: var(--brand-blue);
  background-color: rgba(240, 249, 255, 0.4);
}

.btn-icon-right {
  width: 1rem;
  height: 1rem;
  color: #E0F2FE;
  transition: transform 0.2s ease;
}
.btn-primary:hover .btn-icon-right { transform: translateX(0.25rem); }

.countdowns-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

/* DIGITAL POSTER CARDS */
.lineup-section {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.lineup-header {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 0.75rem;
  border-bottom: 1px solid var(--border-light);
  padding-bottom: 1rem;
}

@media (min-width: 640px) {
  .lineup-header {
    flex-direction: row;
    align-items: flex-end;
    justify-content: space-between;
  }
}

.lineup-subtitle {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--brand-blue);
}

.lineup-title {
  margin-top: 0.25rem;
  font-family: var(--font-serif, var(--font-sans));
  font-size: 1.875rem;
  font-weight: 700;
  letter-spacing: -0.025em;
  color: var(--text-primary);
}
@media (min-width: 640px) { .lineup-title { font-size: 2.25rem; } }

.lineup-count-badge {
  border-radius: var(--radius-xl);
  border: 1px solid var(--brand-blue);
  background-color: var(--bg-primary);
  padding: 0.375rem 1rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--text-primary);
  box-shadow: var(--shadow-sm);
}

.events-grid {
  display: grid;
  gap: 1.5rem;
}
@media (min-width: 640px) { .events-grid { grid-template-columns: repeat(2, 1fr); } }
@media (min-width: 1024px) { .events-grid { grid-template-columns: repeat(3, 1fr); } }

.event-card {
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  overflow: hidden;
  border-radius: var(--radius-2xl);
  border: 1px solid var(--border-light);
  background-color: var(--bg-primary);
  padding: 1.75rem;
  transition: all 0.3s ease;
  text-decoration: none;
  color: inherit;
}

.event-card:hover {
  transform: translateY(-0.25rem);
  border-color: var(--brand-blue);
  box-shadow: var(--shadow-luxury-lg);
}

.event-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid var(--border-light);
  padding-bottom: 0.75rem;
}

.event-code {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.1em;
  color: var(--brand-blue);
}

.event-team-size {
  border-radius: var(--radius-md);
  border: 1px solid var(--border-light);
  background-color: var(--bg-secondary);
  padding: 0.25rem 0.625rem;
  font-family: var(--font-mono);
  font-size: 0.625rem;
  font-weight: 600;
  color: var(--text-secondary);
  width: fit-content;
  align-self: flex-end;
}

.event-card-title-group {
  margin-top: 1rem;
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.event-icon-wrapper {
  display: flex;
  height: 2.5rem;
  width: 2.5rem;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border-dark);
  transition: background-color 0.2s, color 0.2s;
}

.theme-hackathon, .theme-ctf, .theme-games {
  /* we will just set colors generally below to emulate the dynamic utility classes */
  background-color: rgba(240, 249, 255, 1);
  color: var(--brand-blue);
}
.event-card:hover .event-icon-wrapper {
  background-color: var(--text-primary);
  color: var(--bg-primary);
}

.event-icon { width: 1.25rem; height: 1.25rem; }

.event-title {
  font-family: var(--font-serif, var(--font-sans));
  font-size: 1.25rem;
  font-weight: 700;
  color: var(--text-primary);
  transition: color 0.2s;
}

.event-card:hover .event-title { color: var(--brand-blue); }

.event-desc {
  margin-top: 0.75rem;
  font-size: 0.75rem;
  line-height: 1.6;
  color: var(--text-secondary);
}

.event-card-footer {
  margin-top: 1.5rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-top: 1px solid var(--border-light);
  padding-top: 1rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  color: var(--text-muted);
}

.event-venue {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  font-weight: 600;
  color: var(--text-secondary);
}

.event-venue-icon {
  width: 0.875rem;
  height: 0.875rem;
  color: var(--brand-blue);
}

.event-action {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  font-weight: 700;
  color: var(--text-primary);
  transition: all 0.2s;
}

.event-card:hover .event-action {
  transform: translateX(0.25rem);
  color: var(--brand-blue);
}

.event-action-icon { width: 0.875rem; height: 0.875rem; }
</style>
