// src/components/CountdownCard.vue
<script setup>
import { useCountdown } from '../composables/useCountdown'
import { computed } from 'vue'

const props = defineProps({
  label: String,
  target: String,
  caption: String,
  completeLabel: String,
  emphasis: {
    type: Boolean,
    default: false
  }
})

const { isComplete, days, hours, minutes, seconds } = useCountdown(props.target)
const UNITS = ['Days', 'Hours', 'Min', 'Sec']
const values = computed(() => [days.value, hours.value, minutes.value, seconds.value])
</script>

<template>
  <div class="countdown-card">
    <div class="card-header">
      <h3 class="card-title">
        {{ label }}
      </h3>
      <span v-if="emphasis" class="card-badge emphasis-badge">
        KEY DEADLINE
      </span>
      <span v-else class="card-badge">
        EVENT DAY
      </span>
    </div>

    <p v-if="isComplete" class="complete-text">
      {{ completeLabel }}
    </p>
    
    <div v-else class="timer-grid">
      <div v-for="(value, index) in values" :key="UNITS[index]" class="timer-box">
        <div class="timer-value">
          {{ String(value).padStart(2, '0') }}
        </div>
        <div class="timer-label">
          {{ UNITS[index] }}
        </div>
      </div>
    </div>

    <div class="card-footer">
      <p class="caption-text">{{ caption }}</p>
    </div>
  </div>
</template>

<style scoped>
.countdown-card {
  position: relative;
  z-index: 10;
  background-color: var(--bg-primary);
  padding: 0.75rem;
  border: 1px solid var(--border-light);
  border-radius: var(--radius-2xl);
  box-shadow: var(--shadow-sm);
  transition: all 0.2s ease;
}

@media (min-width: 640px) {
  .countdown-card {
    padding: 1.25rem;
  }
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid var(--border-light);
  padding-bottom: 0.5rem;
  margin-bottom: 0.5rem;
}

.card-title {
  font-family: var(--font-serif, var(--font-sans));
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.2em;
  color: var(--text-secondary);
}

.card-badge {
  font-family: var(--font-mono);
  font-size: 0.625rem;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--text-muted);
}

.emphasis-badge {
  color: var(--brand-blue-hover);
}

.complete-text {
  margin-top: 1rem;
  font-family: var(--font-serif, var(--font-sans));
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
}

.timer-grid {
  margin-top: 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  text-align: center;
}

@media (min-width: 640px) {
  .timer-grid {
    gap: 1rem;
  }
}

.timer-box {
  flex: 1;
  padding: 0.25rem 0;
  background-color: var(--bg-secondary);
  border: 1px solid var(--border-light);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-sm);
}

.timer-value {
  font-family: var(--font-mono);
  font-size: 1.875rem;
  font-weight: 900;
  font-variant-numeric: tabular-nums;
  letter-spacing: -0.025em;
  color: var(--text-primary);
}

@media (min-width: 640px) {
  .timer-value {
    font-size: 2.25rem;
  }
}

.timer-label {
  margin-top: 0.25rem;
  font-family: var(--font-mono);
  font-size: 0.625rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--brand-blue);
}

.card-footer {
  margin-top: 1rem;
  padding-top: 0.5rem;
  border-top: 1px solid var(--border-light);
}

.caption-text {
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1.6;
  color: var(--text-muted);
}
</style>

// src/components/CountdownCard.tsx
import React from 'react';
import { useCountdown } from '../hooks/useCountdown';

interface CountdownCardProps {
  label: string;
  target: string;
  caption: string;
  completeLabel: string;
  emphasis?: boolean;
}

const UNITS = ['Days', 'Hours', 'Min', 'Sec'] as const;

export function CountdownCard({
  label,
  target,
  caption,
  completeLabel,
  emphasis = false
}: CountdownCardProps) {
  const countdown = useCountdown(target);
  const values = [countdown.days, countdown.hours, countdown.minutes, countdown.seconds];

  return (
    <div className="relative z-10 bg-transparent p-3 sm:p-5 transition-all duration-200">
      <div className="flex items-center justify-between">
        <h3 className="text-xs font-serif font-bold uppercase tracking-[0.2em] text-[#334155]">
          {label}
        </h3>
        {emphasis ? (
          <span className="text-[10px] font-mono font-bold tracking-widest text-[#0284C7] uppercase">
            ● KEY DEADLINE
          </span>
        ) : (
          <span className="text-[10px] font-mono font-bold tracking-widest text-[#64748B] uppercase">
            ● EVENT DAY
          </span>
        )}
      </div>

      {countdown.isComplete ? (
        <p className="mt-4 font-serif text-2xl font-bold text-[#000000]">
          {completeLabel}
        </p>
      ) : (
        <div className="mt-4 flex items-center justify-between gap-2 sm:gap-4 text-center">
          {values.map((value, index) => (
            <div key={UNITS[index]} className="flex-1 py-1">
              <div className="font-mono text-3xl sm:text-4xl font-black tabular-nums text-[#000000] tracking-tight">
                {String(value).padStart(2, '0')}
              </div>
              <div className="mt-1 text-[10px] font-mono font-bold uppercase tracking-widest text-[#0EA5E9]">
                {UNITS[index]}
              </div>
            </div>
          ))}
        </div>
      )}

      <div className="mt-3 pt-1">
        <p className="text-xs text-[#475569] font-medium leading-relaxed">{caption}</p>
      </div>
    </div>
  );
}
