// src/components/Footer.tsx
import React, { useRef } from 'react';
import { ShieldCheckIcon, PhoneIcon, LockIcon } from 'lucide-react';
import { SUPPORT_LINES } from '../data/events';

interface FooterProps {
  onOpenAdmin?: () => void;
}

export function Footer({ onOpenAdmin }: FooterProps) {
  const clickCount = useRef(0);
  const clickTimer = useRef<NodeJS.Timeout | null>(null);

  function handleSecretLogoClick() {
    clickCount.current += 1;
    if (clickTimer.current) clearTimeout(clickTimer.current);

    if (clickCount.current >= 3) {
      clickCount.current = 0;
      onOpenAdmin?.();
    } else {
      clickTimer.current = setTimeout(() => {
        clickCount.current = 0;
      }, 1200);
    }
  }

  return (
    <footer className="border-t border-[#E2E8F0] bg-[#FFFFFF] py-12 text-[#475569] print:hidden">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-[#E2E8F0] pb-8">
          <div>
            <div
              onClick={handleSecretLogoClick}
              className="flex items-center gap-2 cursor-pointer select-none group"
              title="RYVANTA '26"
            >
              <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#0EA5E9] text-white font-serif font-black text-xs group-hover:scale-105 transition-transform">
                R
              </div>
              <span className="font-serif text-xl font-bold tracking-wider text-[#000000]">
                RYVANTA '26
              </span>
            </div>
            <p className="mt-2 text-xs text-[#64748B] max-w-md">
              Jaya Engineering College · National Level Tech Innovation Challenge — 19 September 2026.
              All competitions and team events held on-campus.
            </p>
          </div>

          <div className="flex flex-col sm:items-end gap-2 text-xs font-mono">
            <span className="text-[10px] font-bold uppercase tracking-widest text-[#0EA5E9]">
              Official Helplines
            </span>
            <div className="flex flex-wrap gap-3">
              {SUPPORT_LINES.map((l, i) => (
                <a
                  key={i}
                  href={`tel:${l.tel}`}
                  className="inline-flex items-center gap-1.5 text-[#000000] font-bold hover:text-[#0EA5E9] transition-colors"
                >
                  <PhoneIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                  <span>{l.number}</span>
                </a>
              ))}
            </div>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-mono text-[#64748B]">
          <div className="flex items-center gap-2">
            <ShieldCheckIcon className="h-4 w-4 text-[#0EA5E9]" />
            <span>Secure Automated Registration &amp; Sequential ID Engine</span>
          </div>

          <div className="flex items-center gap-3">
            <p>© 2026 RYVANTA Organizing Committee · Jaya Engineering College. All rights reserved.</p>
            {/* Discrete Secret Lock Button for Organizers */}
            <button
              type="button"
              onClick={onOpenAdmin}
              className="text-[#CBD5E1] hover:text-[#0EA5E9] p-1 transition-colors"
              title="Organizer Portal"
              aria-label="Organizer Portal"
            >
              <LockIcon className="h-3 w-3" />
            </button>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;

// src/components/Footer.vue
<script setup>
import { ref } from "vue";
import { ShieldCheckIcon, PhoneIcon, LockIcon } from "lucide-vue-next";
import { SUPPORT_LINES } from "../data/events.js";

let clickCount = 0;
let clickTimer = null;

function handleSecretLogoClick() {
	clickCount++;
	if (clickCount === 1) {
		clickTimer = setTimeout(() => {
			clickCount = 0;
		}, 2000);
	} else if (clickCount >= 5) {
		clearTimeout(clickTimer);
		clickCount = 0;
		alert("Terminal Access Granted...");
	}
}
</script>

<template>
	<footer class="footer">
		<div class="footer-container">
			<div class="footer-grid">
				<!-- Brand & Identity -->
				<div class="footer-brand">
					<div class="brand-logo" @click="handleSecretLogoClick">
						<span class="brand-title">RYVANTA '26</span>
					</div>
					<p class="brand-desc">
						Tech innovation challenge hosted at Jaya Engineering
						College.
					</p>
				</div>

				<!-- Quick Contacts -->
				<div class="footer-contacts">
					<h4 class="section-title">Priority Support Lines</h4>
					<ul class="contact-list">
						<li
							v-for="(contact, index) in SUPPORT_LINES.slice(
								0,
								2,
							)"
							:key="index"
							class="contact-item"
						>
							<PhoneIcon class="contact-icon" />
							<div class="contact-info">
								<span class="contact-name">{{
									contact.label
								}}</span>
								<span class="contact-phone">{{
									contact.number
								}}</span>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</template>

<style scoped>
.footer {
	margin-top: 4rem;
	border-top: 1px solid var(--border-light);
	background-color: var(--bg-primary);
	padding: 3rem 0 1.5rem;
}

.footer-container {
	width: 100%;
	max-width: 1200px;
	margin: 0 auto;
	padding: 0 1rem;
}

.footer-grid {
	display: grid;
	gap: 3rem;
}

@media (min-width: 768px) {
	.footer-grid {
		grid-template-columns: repeat(2, 1fr);
	}
}

.footer-brand {
	display: flex;
	flex-direction: column;
	gap: 1rem;
}

.brand-logo {
	display: flex;
	align-items: center;
	gap: 1rem;
	cursor: pointer;
}

.brand-title {
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1.5rem;
	font-weight: 900;
	letter-spacing: -0.025em;
	color: var(--text-primary);
}

.brand-badge {
	display: inline-flex;
	align-items: center;
	gap: 0.375rem;
	border-radius: var(--radius-full);
	background-color: var(--brand-blue-light);
	padding: 0.25rem 0.75rem;
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--brand-blue-hover);
}

.brand-icon {
	width: 0.875rem;
	height: 0.875rem;
}

.brand-desc {
	font-size: 0.875rem;
	color: var(--text-muted);
	max-width: 24rem;
	line-height: 1.6;
}

.footer-contacts {
	display: flex;
	flex-direction: column;
	gap: 1.5rem;
}

.section-title {
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-primary);
}

.contact-list {
	display: grid;
	gap: 1rem;
}

@media (min-width: 640px) {
	.contact-list {
		grid-template-columns: repeat(2, 1fr);
	}
}

.contact-item {
	display: flex;
	align-items: flex-start;
	gap: 0.75rem;
}

.contact-icon {
	width: 1.25rem;
	height: 1.25rem;
	color: var(--text-muted);
	flex-shrink: 0;
	margin-top: 0.25rem;
}

.contact-info {
	display: flex;
	flex-direction: column;
	gap: 0.25rem;
}

.contact-name {
	font-size: 0.875rem;
	font-weight: 600;
	color: var(--text-primary);
}

.contact-role {
	font-size: 0.75rem;
	color: var(--text-muted);
}

.contact-phone {
	font-family: var(--font-mono);
	font-size: 0.875rem;
	color: var(--brand-blue);
}

.footer-bottom {
	margin-top: 4rem;
	border-top: 1px solid var(--border-light);
	padding-top: 1.5rem;
}

.footer-bottom-inner {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: space-between;
	gap: 1rem;
}

@media (min-width: 640px) {
	.footer-bottom-inner {
		flex-direction: row;
	}
}

.security-badge {
	display: flex;
	align-items: center;
	gap: 0.375rem;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-muted);
}

.security-icon {
	width: 0.875rem;
	height: 0.875rem;
}
</style>
