// src/components/Header.tsx
import React, { useRef } from 'react';
import { NavLink, Link } from 'react-router-dom';
import { TrophyIcon } from 'lucide-react';

const NAV_ITEMS = [
  { to: '/', label: 'Home' },
  { to: '/events', label: 'Events & Registration' },
  { to: '/support', label: 'Helpdesk & Support' }
];

interface HeaderProps {
  onOpenAdmin: () => void;
}

export function Header({ onOpenAdmin }: HeaderProps) {
  const clickCount = useRef(0);
  const clickTimer = useRef<NodeJS.Timeout | null>(null);

  // Secret 3-Click Admin Trigger on Brand Logo
  function handleSecretLogoClick(e: React.MouseEvent) {
    clickCount.current += 1;
    if (clickTimer.current) clearTimeout(clickTimer.current);

    if (clickCount.current >= 3) {
      clickCount.current = 0;
      onOpenAdmin();
    } else {
      clickTimer.current = setTimeout(() => {
        clickCount.current = 0;
      }, 1200);
    }
  }

  return (
    <header className="sticky top-0 z-40 border-b border-[#E2E8F0] bg-[#FFFFFF]/95 backdrop-blur-md shadow-sm">
      <div className="mx-auto flex h-20 w-full max-w-7xl items-center justify-between gap-6 px-4 sm:px-6 lg:px-8">
        {/* Brand Logo & College Title (Secret 3-Click Admin Trigger) */}
        <div
          onClick={handleSecretLogoClick}
          className="flex items-center gap-3 group cursor-pointer select-none"
          title="RYVANTA '26"
        >
          <NavLink to="/" className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-[#0EA5E9] to-[#2563EB] text-[#FFFFFF] font-serif font-black text-lg shadow-md transition-transform duration-200 group-hover:scale-105">
              R
            </div>
            <div className="flex flex-col">
              <div className="flex items-baseline gap-1.5">
                <span className="font-serif text-2xl font-black tracking-wider text-[#000000]">
                  RYVANTA
                </span>
                <span className="font-mono text-xs font-bold text-[#0EA5E9]">'26</span>
              </div>
              <span className="text-[10px] font-sans font-semibold tracking-wider text-[#64748B] uppercase line-clamp-1">
                Jaya Engineering College · National Level Tech Innovation Challenge
              </span>
            </div>
          </NavLink>
        </div>

        {/* Navigation */}
        <nav aria-label="Primary" className="hidden items-center gap-1.5 md:flex">
          {NAV_ITEMS.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.to === '/'}
              className={({ isActive }) =>
                [
                  'whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold uppercase tracking-wider transition-all duration-200',
                  isActive
                    ? 'border border-[#0EA5E9] bg-[#000000] text-[#FFFFFF] font-bold shadow-md ring-2 ring-[#0EA5E9]/30'
                    : 'text-[#475569] hover:bg-[#F8FAFC] hover:text-[#000000]'
                ].join(' ')
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>

        {/* Right CTA for Students (Clean & Free of Admin Controls) */}
        <div className="flex items-center gap-3">
          <Link
            to="/events"
            className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-[#0EA5E9] to-[#2563EB] px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-[#FFFFFF] shadow-md hover:from-[#0284C7] hover:to-[#1D4ED8] transition-all duration-200 hover:shadow-blue-glow"
          >
            <TrophyIcon className="h-3.5 w-3.5 text-[#E0F2FE]" />
            <span>Register Team</span>
          </Link>
        </div>
      </div>

      {/* Mobile Bar */}
      <nav
        aria-label="Primary mobile"
        className="flex border-t border-[#E2E8F0] bg-[#FFFFFF]/95 md:hidden"
      >
        {NAV_ITEMS.map((item) => (
          <NavLink
            key={item.to}
            to={item.to}
            end={item.to === '/'}
            className={({ isActive }) =>
              [
                'flex-1 whitespace-nowrap py-3 text-center text-xs font-semibold uppercase tracking-wider transition-colors',
                isActive ? 'text-[#0EA5E9] border-b-2 border-[#0EA5E9] font-bold' : 'text-[#64748B]'
              ].join(' ')
            }
          >
            {item.label}
          </NavLink>
        ))}
      </nav>
    </header>
  );
}

export default Header;

// src/components/Header.vue
<script setup>
import { ref } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { TrophyIcon } from "lucide-vue-next";

const route = useRoute();
let clickCount = 0;
let clickTimer = null;

const NAV_ITEMS = [
	{ to: "/", label: "Home" },
	{ to: "/#events-lineup", label: "Events & Registration" },
	{ to: "/about", label: "About Us" },
	{ to: "/support", label: "Helpdesk & Support" },
];

function handleLogoClick() {
	clickCount++;
	if (clickCount === 1) {
		clickTimer = setTimeout(() => {
			clickCount = 0;
		}, 2000);
	} else if (clickCount >= 7) {
		clearTimeout(clickTimer);
		clickCount = 0;
		alert("Easter Egg Found...");
	}
}
</script>

<template>
	<header class="header">
		<div class="header-container">
			<div class="header-inner">
				<!-- Logo -->
				<RouterLink to="/" class="logo-group" @click="handleLogoClick">
					<div class="logo-icon-wrapper">
						<TrophyIcon class="logo-icon" />
					</div>
					<div class="logo-text">
						<span class="logo-title">RYVANTA '26</span>
						<span class="logo-subtitle"
							>Tech Innovation Challenge</span
						>
					</div>
				</RouterLink>

				<!-- Navigation (Desktop) -->
				<nav class="desktop-nav">
					<RouterLink
						v-for="item in NAV_ITEMS"
						:key="item.label"
						:to="item.to"
						class="nav-link"
						:class="{
							active:
								route.path === item.to ||
								(route.path === '/' &&
									item.to === '/#events-lineup' &&
									route.hash === '#events-lineup'),
						}"
					>
						{{ item.label }}
					</RouterLink>
				</nav>

				<!-- CTA Action -->
				<div class="cta-wrapper">
					<RouterLink to="/register" class="cta-button">
						<TrophyIcon class="cta-icon" />
						<span>Register Team</span>
					</RouterLink>
				</div>
			</div>
		</div>

		<!-- Navigation (Mobile - Bottom Scrollable) -->
		<div class="mobile-nav">
			<nav class="mobile-nav-inner">
				<RouterLink
					v-for="item in NAV_ITEMS"
					:key="item.label"
					:to="item.to"
					class="mobile-nav-link"
					:class="{
						active:
							route.path === item.to ||
							(route.path === '/' &&
								item.to === '/#events-lineup' &&
								route.hash === '#events-lineup'),
					}"
				>
					{{ item.label }}
				</RouterLink>
			</nav>
		</div>
	</header>
</template>

<style scoped>
.header {
	position: sticky;
	top: 0;
	z-index: 50;
	width: 100%;
	backdrop-filter: blur(12px);
	background-color: rgba(255, 255, 255, 0.8);
	border-bottom: 1px solid var(--border-light);
}

.header-container {
	width: 100%;
	max-width: 1200px;
	margin: 0 auto;
	padding: 0 1rem;
}

.header-inner {
	display: flex;
	height: 4rem;
	align-items: center;
	justify-content: space-between;
	gap: 1rem;
}

/* Logo */
.logo-group {
	display: flex;
	align-items: center;
	gap: 0.75rem;
	transition: transform 0.2s ease;
}

.logo-group:active {
	transform: scale(0.98);
}

.logo-icon-wrapper {
	display: flex;
	height: 2.5rem;
	width: 2.5rem;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-lg);
	background-color: var(--brand-blue);
	color: #ffffff;
	box-shadow: var(--shadow-sm);
}

.logo-icon {
	width: 1.25rem;
	height: 1.25rem;
}

.logo-text {
	display: flex;
	flex-direction: column;
}

.logo-title {
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1.125rem;
	font-weight: 900;
	letter-spacing: -0.025em;
	color: var(--text-primary);
}

.logo-subtitle {
	display: none;
	font-size: 0.625rem;
	font-weight: 600;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-muted);
}

@media (min-width: 768px) {
	.logo-subtitle {
		display: block;
	}
}

/* Desktop Nav */
.desktop-nav {
	display: none;
	align-items: center;
	gap: 1.5rem;
}

@media (min-width: 1024px) {
	.desktop-nav {
		display: flex;
	}
}

.nav-link {
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-muted);
	transition: color 0.2s ease;
}

.nav-link:hover,
.nav-link.active {
	color: var(--brand-blue);
}

/* CTA */
.cta-wrapper {
	display: flex;
	align-items: center;
	gap: 1rem;
}

.cta-button {
	display: inline-flex;
	align-items: center;
	gap: 0.375rem;
	border-radius: var(--radius-lg);
	background-color: var(--bg-primary);
	border: 1px solid var(--border-light);
	padding: 0.5rem 0.75rem;
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-primary);
	box-shadow: var(--shadow-sm);
	transition: all 0.2s ease;
}

.cta-button:hover {
	border-color: var(--brand-blue);
	color: var(--brand-blue);
	box-shadow: var(--shadow-blue-glow);
}

.cta-icon {
	width: 1rem;
	height: 1rem;
}

/* Mobile Nav */
.mobile-nav {
	display: block;
	border-top: 1px solid var(--border-light);
	background-color: rgba(255, 255, 255, 0.9);
}

@media (min-width: 1024px) {
	.mobile-nav {
		display: none;
	}
}

.mobile-nav-inner {
	display: flex;
	overflow-x: auto;
	padding: 0.75rem 1rem;
	gap: 1.5rem;
	white-space: nowrap;
}

.mobile-nav-link {
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-muted);
	transition: color 0.2s ease;
}

.mobile-nav-link:hover,
.mobile-nav-link.active {
	color: var(--brand-blue);
}
</style>
