// src/components/PaymentQrBox.vue
<script setup>
import { ref } from "vue";
import {
	ExternalLinkIcon,
	SmartphoneIcon,
	ShieldCheckIcon,
	CheckCircle2Icon,
	LockIcon,
} from "lucide-vue-next";

const props = defineProps({
	upiId: { type: String, default: "alangaram1985@okicici" },
	payeeName: { type: String, default: "Alangaram Selvaraj" },
	feeAmount: { type: Number, required: true },
	eventName: { type: String, required: true },
	teamName: { type: String, default: "" },
	userUpiId: { type: String, default: "" },
	upiRef: { type: String, default: "" },
	hideQrCode: { type: Boolean, default: false },
});

const emit = defineEmits(["update:userUpiId", "update:upiRef"]);

const note = `RYVANTA ${props.eventName.slice(0, 12)}${props.teamName ? ` - ${props.teamName.slice(0, 10)}` : ""}`;
const baseUpiParams = `pa=${encodeURIComponent(props.upiId)}&pn=${encodeURIComponent(props.payeeName)}&am=${props.feeAmount}&cu=INR&tn=${encodeURIComponent(note)}`;

const genericUpiUri = `upi://pay?${baseUpiParams}`;
const gpayUri = `gpay://upi/pay?${baseUpiParams}`;
const phonepeUri = `phonepe://pay?${baseUpiParams}`;
const paytmUri = `paytmmp://pay?${baseUpiParams}`;

function handleUserUpiIdChange(e) {
	emit("update:userUpiId", e.target.value);
}

function handleUpiRefChange(e) {
	emit("update:upiRef", e.target.value.replace(/[^a-zA-Z0-9]/g, ""));
}
</script>

<template>
	<div class="payment-box">
		<!-- Payee Profile Header Bar -->
		<div class="payment-header">
			<div class="header-left">
				<div class="header-icon-wrapper">
					<ShieldCheckIcon class="header-icon" />
				</div>
				<div>
					<h3 class="header-title">
						Official Challenge Payment Gateway
					</h3>
					<span class="header-subtitle"
						>Automated Authentication &amp; Payment Received
						Verification</span
					>
				</div>
			</div>

			<div class="fee-badge">
				<span class="fee-label">Fee Amount:</span>
				<span class="fee-value">₹{{ feeAmount }}</span>
			</div>
		</div>

		<div class="payment-grid" :class="{ 'grid-full': hideQrCode }">
			<!-- QR Code Container -->
			<div v-if="!hideQrCode" class="qr-column">
				<div class="qr-image-wrapper">
					<img
						src="/images/payment-qr.jpg"
						alt="Payment QR Code"
						class="qr-image"
					/>
				</div>
				<span class="qr-instruction">Scan with any UPI App</span>
				<span class="qr-apps">GPay · PhonePe · Paytm · BHIM</span>
			</div>

			<!-- Secure Gateway Channel Details & Deep Links -->
			<div class="details-column">
				<!-- Secure Channel Card -->
				<div class="secure-card">
					<div class="secure-card-header">
						<span class="secure-title">
							<LockIcon class="secure-icon" />
							Encrypted UPI Gateway
						</span>
					</div>
					<p class="secure-desc">
						Scan the QR code with any UPI app or tap one of the
						direct app buttons below to pay the ₹{{ feeAmount }}
						challenge fee. Once paid, enter your UPI ID and the
						12-digit UTR reference below to verify that payment has
						been received.
					</p>
				</div>

				<!-- Quick Pay Buttons for Mobile -->
				<div class="quick-pay-section">
					<span class="quick-pay-label">
						Direct App Deep-Links (Mobile Only)
					</span>
					<div class="quick-pay-grid">
						<a :href="gpayUri" class="app-button">
							<SmartphoneIcon class="app-icon" />
							<span>Google Pay</span>
						</a>
						<a :href="phonepeUri" class="app-button">
							<SmartphoneIcon class="app-icon" />
							<span>PhonePe</span>
						</a>
						<a :href="paytmUri" class="app-button">
							<SmartphoneIcon class="app-icon" />
							<span>Paytm</span>
						</a>
						<a
							:href="genericUpiUri"
							class="app-button primary-app-button"
						>
							<ExternalLinkIcon class="app-icon" />
							<span>Any UPI App</span>
						</a>
					</div>
				</div>
			</div>
		</div>

		<!-- Payment Authentication, UTR & Screenshot Proof Section -->
		<div class="auth-section">
			<div class="auth-header">
				<div class="auth-title-wrapper">
					<LockIcon class="auth-icon" />
					<span class="auth-title">
						Payment Authentication &amp; Verification Proof
						<span class="required-asterisk">*</span>
					</span>
				</div>
			</div>

			<div class="auth-grid">
				<!-- User UPI ID -->
				<div class="input-group">
					<label class="input-label">
						<span>Your UPI ID</span>
					</label>
					<input
						type="text"
						:value="userUpiId"
						@input="handleUserUpiIdChange"
						placeholder="e.g. 9876543210@ybl"
						class="auth-input"
						:class="
							userUpiId.trim().length > 3 &&
							userUpiId.includes('@')
								? 'input-valid'
								: ''
						"
					/>
				</div>

				<!-- UPI Ref / 12-Digit UTR Number -->
				<div class="input-group">
					<label class="input-label">
						<span>12-Digit UPI Transaction ID (UTR)</span>
					</label>
					<input
						type="text"
						:value="upiRef"
						@input="handleUpiRefChange"
						placeholder="e.g. 423984729182 (12-digit UTR)"
						maxlength="24"
						class="auth-input"
						:class="upiRef.trim().length >= 8 ? 'input-valid' : ''"
					/>
				</div>
			</div>

			<p class="security-note">
				<LockIcon class="security-note-icon" />
				<span
					>Your UPI ID and 12-digit UTR reference are authenticated
					and stored to verify that your ₹{{ feeAmount }} registration
					payment has been received before issuing your official
					Student ID.</span
				>
			</p>
		</div>
	</div>
</template>

<style scoped>
.payment-box {
	overflow: hidden;
	border-radius: var(--radius-2xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-primary);
	padding: 1.25rem;
	box-shadow: var(--shadow-luxury);
}

@media (min-width: 640px) {
	.payment-box {
		padding: 1.75rem;
	}
}

.payment-header {
	display: flex;
	flex-direction: column;
	align-items: flex-start;
	gap: 0.75rem;
	border-bottom: 1px solid var(--border-light);
	padding-bottom: 1rem;
}

@media (min-width: 640px) {
	.payment-header {
		flex-direction: row;
		align-items: center;
		justify-content: space-between;
	}
}

.header-left {
	display: flex;
	align-items: center;
	gap: 0.75rem;
}

.header-icon-wrapper {
	display: flex;
	height: 2.5rem;
	width: 2.5rem;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-xl);
	background-color: var(--bg-secondary);
	border: 1px solid var(--border-dark);
}

.header-icon {
	width: 1.25rem;
	height: 1.25rem;
	color: var(--brand-blue);
}

.header-title {
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1rem;
	font-weight: 700;
	color: var(--text-primary);
}

.header-subtitle {
	font-size: 0.75rem;
	color: var(--text-muted);
}

.fee-badge {
	display: flex;
	align-items: center;
	gap: 0.5rem;
	border-radius: var(--radius-xl);
	background-color: var(--brand-blue-light);
	border: 1px solid var(--brand-blue);
	padding: 0.5rem 1rem;
}

.fee-label {
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--brand-blue-hover);
}

.fee-value {
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1.25rem;
	font-weight: 900;
	color: var(--text-primary);
}

.payment-grid {
	margin-top: 1.5rem;
	display: grid;
	gap: 1.5rem;
	align-items: flex-start;
}

@media (min-width: 768px) {
	.payment-grid {
		grid-template-columns: 220px minmax(0, 1fr);
	}
	.grid-full {
		grid-template-columns: 1fr;
	}
}

.qr-column {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-2xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 1rem;
	text-align: center;
}

.qr-image-wrapper {
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-dark);
	background-color: var(--bg-primary);
	padding: 0.5rem;
	box-shadow: var(--shadow-md);
}

.qr-image {
	width: 168px;
	height: 168px;
	object-fit: cover;
	border-radius: var(--radius-lg);
}

.qr-instruction {
	margin-top: 0.75rem;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-muted);
}

.qr-apps {
	margin-top: 0.125rem;
	font-size: 0.6875rem;
	font-weight: 500;
	color: var(--brand-blue-hover);
}

.details-column {
	display: flex;
	flex-direction: column;
	gap: 1rem;
}

.secure-card {
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 1rem;
}

.secure-card-header {
	display: flex;
	align-items: center;
	justify-content: space-between;
}

.secure-title {
	display: flex;
	align-items: center;
	gap: 0.375rem;
	font-family: var(--font-mono);
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-primary);
}

.secure-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--brand-blue);
}

.live-badge {
	border-radius: var(--radius-full);
	background-color: var(--bg-secondary);
	border: 1px solid var(--success);
	padding: 0.125rem 0.625rem;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	color: var(--success);
}

.secure-desc {
	margin-top: 0.5rem;
	font-size: 0.75rem;
	line-height: 1.6;
	color: var(--text-muted);
}

.quick-pay-section {
	display: flex;
	flex-direction: column;
}

.quick-pay-label {
	margin-bottom: 0.5rem;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--text-muted);
}

.quick-pay-grid {
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 0.5rem;
}

@media (min-width: 640px) {
	.quick-pay-grid {
		grid-template-columns: repeat(4, 1fr);
	}
}

.app-button {
	display: flex;
	align-items: center;
	justify-content: center;
	gap: 0.375rem;
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 0.625rem;
	font-size: 0.75rem;
	font-weight: 600;
	color: var(--text-primary);
	transition: all 0.2s ease;
	box-shadow: var(--shadow-sm);
}

.app-button:hover {
	border-color: var(--brand-blue);
	background-color: var(--bg-primary);
}

.primary-app-button {
	border-color: var(--brand-blue);
	background-color: var(--brand-blue-light);
}

.primary-app-button:hover {
	background-color: var(--brand-blue-light);
}

.app-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--brand-blue);
}

.auth-section {
	margin-top: 1.5rem;
	border-top: 1px solid var(--border-light);
	padding-top: 1.25rem;
}

.auth-header {
	margin-bottom: 0.75rem;
	display: flex;
	flex-direction: column;
	gap: 0.5rem;
}

@media (min-width: 640px) {
	.auth-header {
		flex-direction: row;
		align-items: center;
		justify-content: space-between;
	}
}

.auth-title-wrapper {
	display: flex;
	align-items: center;
	gap: 0.375rem;
}

.auth-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--brand-blue);
}

.auth-title {
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--text-primary);
}

.required-asterisk {
	color: var(--error);
}

.status-ready {
	display: flex;
	align-items: center;
	gap: 0.25rem;
	font-family: var(--font-mono);
	font-size: 0.6875rem;
	font-weight: 700;
	color: var(--success);
}

.status-icon {
	width: 0.875rem;
	height: 0.875rem;
}

.status-pending {
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 600;
	color: var(--warning);
}

.auth-grid {
	display: grid;
	gap: 1rem;
}

@media (min-width: 640px) {
	.auth-grid {
		grid-template-columns: repeat(2, 1fr);
	}
}

.input-group {
	display: flex;
	flex-direction: column;
}

.input-label {
	display: flex;
	align-items: center;
	justify-content: space-between;
	margin-bottom: 0.375rem;
	font-size: 0.75rem;
	font-weight: 600;
	color: var(--text-secondary);
}

.valid-badge {
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	color: var(--success);
}

.auth-input {
	width: 100%;
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 0.625rem 1rem;
	font-family: var(--font-mono);
	font-size: 0.75rem;
	color: var(--text-primary);
	transition: all 0.2s ease;
}

.auth-input:focus {
	outline: none;
	border-color: var(--brand-blue);
	background-color: var(--bg-primary);
}

.input-valid {
	border-color: var(--success);
	background-color: var(--success-bg);
}
.input-valid:focus {
	border-color: var(--success);
}

.security-note {
	margin-top: 0.75rem;
	display: flex;
	align-items: flex-start;
	gap: 0.375rem;
	font-size: 0.6875rem;
	color: var(--text-muted);
}
.security-note-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--text-muted);
	flex-shrink: 0;
}
</style>

// src/components/PaymentQrBox.tsx
import React, { useState, useRef } from 'react';
import {
  ExternalLinkIcon,
  SmartphoneIcon,
  UploadCloudIcon,
  FileImageIcon,
  XIcon,
  ShieldCheckIcon,
  CheckCircle2Icon,
  LockIcon
} from 'lucide-react';
interface PaymentQrBoxProps {
  upiId?: string;
  payeeName?: string;
  feeAmount: number;
  eventName: string;
  teamName?: string;
  upiRef?: string;
  onUpiRefChange?: (val: string) => void;
  paymentScreenshot?: string;
  onScreenshotChange?: (base64: string | undefined) => void;
  hideQrCode?: boolean;
}

export function PaymentQrBox({
  upiId = 'alangaram1985@okicici',
  payeeName = 'Alangaram Selvaraj',
  feeAmount,
  eventName,
  teamName,
  upiRef = '',
  onUpiRefChange,
  paymentScreenshot,
  onScreenshotChange,
  hideQrCode = false
}: PaymentQrBoxProps) {
  const [uploadError, setUploadError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Construct standard UPI payment URI (encrypted in QR code and direct deep links)
  const note = `RYVANTA ${eventName.slice(0, 12)}${teamName ? ` - ${teamName.slice(0, 10)}` : ''}`;
  const baseUpiParams = `pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(
    payeeName
  )}&am=${feeAmount}&cu=INR&tn=${encodeURIComponent(note)}`;

  // Generic and App-specific deep links
  const genericUpiUri = `upi://pay?${baseUpiParams}`;
  const gpayUri = `gpay://upi/pay?${baseUpiParams}`;
  const phonepeUri = `phonepe://pay?${baseUpiParams}`;
  const paytmUri = `paytmmp://pay?${baseUpiParams}`;

  function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      setUploadError('Please select a valid image file (PNG, JPG, JPEG, WEBP).');
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      setUploadError('Image size exceeds 5MB limit.');
      return;
    }

    setUploadError(null);
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string' && onScreenshotChange) {
        onScreenshotChange(reader.result);
      }
    };
    reader.readAsDataURL(file);
  }

  function handleRemoveScreenshot() {
    if (onScreenshotChange) {
      onScreenshotChange(undefined);
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }

  const isUtrValid = upiRef.trim().length >= 8;
  const hasProof = isUtrValid || Boolean(paymentScreenshot);

  return (
    <div className="overflow-hidden rounded-2xl border border-[#E2E8F0] bg-[#FFFFFF] p-5 sm:p-7 shadow-luxury">
      {/* Payee Profile Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-[#E2E8F0] pb-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0EA5E9] font-bold">
            <ShieldCheckIcon className="h-5 w-5 text-[#0EA5E9]" />
          </div>
          <div>
            <h3 className="font-serif text-base font-bold text-[#000000]">
              Official Challenge Payment Gateway
            </h3>
            <span className="text-xs text-[#64748B]">Automated Authentication &amp; Payment Received Verification</span>
          </div>
        </div>

        <div className="flex items-center gap-2 rounded-xl bg-sky-50/80 border border-[#0EA5E9] px-4 py-2 text-right">
          <span className="text-[10px] uppercase font-mono font-bold tracking-widest text-[#0284C7]">
            Fee Amount:
          </span>
          <span className="font-serif text-xl font-black text-[#000000]">
            ₹{feeAmount}
          </span>
        </div>
      </div>

      <div className={`mt-6 grid gap-6 ${hideQrCode ? 'grid-cols-1' : 'md:grid-cols-[220px_minmax(0,1fr)]'} items-start`}>
        {/* QR Code Container (hidden if hideQrCode is true) */}
        {!hideQrCode && (
          <div className="flex flex-col items-center justify-center rounded-2xl border border-[#E2E8F0] bg-[#F8FAFC] p-4 text-center">
            <div className="rounded-xl border border-[#CBD5E1] bg-[#FFFFFF] p-2 shadow-md">
              <img src="/images/payment-qr.jpg" alt="Payment QR Code" className="w-[168px] h-[168px] object-cover rounded-lg" />
            </div>

            <span className="mt-3 font-mono text-[10px] font-bold uppercase tracking-wider text-[#64748B]">
              Scan with any UPI App
            </span>
            <span className="mt-0.5 text-[11px] font-medium text-[#0284C7]">GPay · PhonePe · Paytm · BHIM</span>
          </div>
        )}

        {/* Secure Gateway Channel Details & Deep Links */}
        <div className="space-y-4">
          {/* Secure Channel Card */}
          <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-4">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-1.5 text-xs font-mono font-bold uppercase tracking-wider text-[#000000]">
                <LockIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                Encrypted UPI Gateway
              </span>
              <span className="rounded-full bg-emerald-50 border border-emerald-300 px-2.5 py-0.5 text-[10px] font-mono text-emerald-700 font-bold">
                ● Live &amp; Active
              </span>
            </div>
            <p className="mt-2 text-xs text-[#475569] leading-relaxed">
              Scan the QR code with any UPI app or tap one of the direct app buttons below to pay the ₹{feeAmount} challenge fee. Once paid, enter your 12-digit UTR reference or attach your payment receipt screenshot below to verify that payment has been received.
            </p>
          </div>

          {/* Quick Pay Buttons for Mobile */}
          <div>
            <span className="mb-2 block text-[10px] font-mono font-bold uppercase tracking-widest text-[#64748B]">
              Direct App Deep-Links (Mobile Only)
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              <a
                href={gpayUri}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-2.5 text-xs font-semibold text-[#000000] hover:border-[#0EA5E9] hover:bg-[#FFFFFF] transition-colors shadow-sm"
              >
                <SmartphoneIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                <span>Google Pay</span>
              </a>
              <a
                href={phonepeUri}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-2.5 text-xs font-semibold text-[#000000] hover:border-[#0EA5E9] hover:bg-[#FFFFFF] transition-colors shadow-sm"
              >
                <SmartphoneIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                <span>PhonePe</span>
              </a>
              <a
                href={paytmUri}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-2.5 text-xs font-semibold text-[#000000] hover:border-[#0EA5E9] hover:bg-[#FFFFFF] transition-colors shadow-sm"
              >
                <SmartphoneIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                <span>Paytm</span>
              </a>
              <a
                href={genericUpiUri}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[#0EA5E9] bg-sky-50 p-2.5 text-xs font-bold text-[#000000] hover:bg-sky-100 transition-colors shadow-sm"
              >
                <ExternalLinkIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
                <span>Any UPI App</span>
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Payment Authentication, UTR & Screenshot Proof Section */}
      <div className="mt-6 border-t border-[#E2E8F0] pt-5">
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-1.5">
            <LockIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
            <span className="text-xs font-bold uppercase tracking-wider text-[#000000]">
              Payment Authentication &amp; Verification Proof <span className="text-red-500">*</span>
            </span>
          </div>
          {hasProof ? (
            <span className="flex items-center gap-1 text-[11px] font-mono font-bold text-emerald-600">
              <CheckCircle2Icon className="h-3.5 w-3.5" />
              Proof Ready to Verify Payment
            </span>
          ) : (
            <span className="text-[10px] font-mono text-amber-600 font-semibold">
              (Required to check payment received)
            </span>
          )}
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          {/* UPI Ref / 12-Digit UTR Number */}
          <div>
            <label
              htmlFor="upi-ref"
              className="mb-1.5 flex items-center justify-between text-xs font-semibold text-[#334155]"
            >
              <span>12-Digit UPI UTR / Ref Number</span>
              {isUtrValid && (
                <span className="text-[10px] font-mono text-emerald-600 font-bold">✓ Valid Format</span>
              )}
            </label>
            <input
              id="upi-ref"
              type="text"
              value={upiRef}
              onChange={(e) => onUpiRefChange?.(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
              placeholder="e.g. 423984729182 (12-digit UTR)"
              maxLength={24}
              className={`w-full rounded-xl border px-4 py-2.5 font-mono text-xs text-[#000000] placeholder:text-[#64748B] focus:outline-none transition-colors ${
                isUtrValid
                  ? 'border-emerald-400 bg-emerald-50/30 focus:border-emerald-500'
                  : 'border-[#E2E8F0] bg-[#F8FAFC] focus:border-[#0EA5E9] focus:bg-[#FFFFFF]'
              }`}
            />
          </div>

          {/* Screenshot Receipt Upload */}
          <div>
            <label className="mb-1.5 flex items-center justify-between text-xs font-semibold text-[#334155]">
              <span>Payment Screenshot Receipt</span>
              {paymentScreenshot && (
                <span className="text-[10px] font-mono text-emerald-600 font-bold">✓ Receipt Attached</span>
              )}
            </label>
            <input
              type="file"
              ref={fileInputRef}
              accept="image/*"
              onChange={handleFileSelect}
              className="hidden"
            />

            {!paymentScreenshot ? (
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#CBD5E1] bg-[#F8FAFC] px-4 py-2.5 text-xs font-semibold text-[#000000] hover:border-[#0EA5E9] hover:bg-[#FFFFFF] transition-colors"
              >
                <UploadCloudIcon className="h-4 w-4 text-[#0EA5E9]" />
                <span>Attach Payment Screenshot</span>
              </button>
            ) : (
              <div className="flex items-center justify-between rounded-xl border border-emerald-300 bg-emerald-50/80 px-3 py-2 text-xs text-emerald-900">
                <div className="flex items-center gap-2 truncate">
                  <FileImageIcon className="h-4 w-4 shrink-0 text-emerald-600" />
                  <span className="truncate font-mono font-medium">Receipt screenshot attached</span>
                </div>
                <button
                  type="button"
                  onClick={handleRemoveScreenshot}
                  className="rounded-lg p-1 text-emerald-800 hover:bg-emerald-100"
                  title="Remove screenshot"
                >
                  <XIcon className="h-3.5 w-3.5" />
                </button>
              </div>
            )}

            {uploadError && <p className="mt-1 text-[11px] text-red-600">{uploadError}</p>}
          </div>
        </div>

        <p className="mt-3 text-[11px] text-[#64748B] flex items-center gap-1.5">
          <span>🔒</span>
          <span>Your 12-digit UTR reference or screenshot receipt is authenticated and stored to verify that your ₹{feeAmount} registration payment has been received before issuing your official Student ID.</span>
        </p>
      </div>
    </div>
  );
}

export default PaymentQrBox;
