// src/components/RyvantaIntroLoader.tsx
import React, { useEffect, useState, useRef } from 'react';
import { SparklesIcon, LogInIcon, ArrowRightIcon, CpuIcon } from 'lucide-react';
import { playPortalLoginSound } from '../services/portalSound';

interface LetterConfig {
  char: string;
  fromX: number; // in vw
  fromY: number; // in vh
  rotate: number; // in deg
  delay: number; // in ms
}

const LETTERS_CONFIG: LetterConfig[] = [
  { char: 'R', fromX: -120, fromY: -120, rotate: -45, delay: 150 }, // Top-Left
  { char: 'Y', fromX: 0, fromY: -140, rotate: 0, delay: 280 },     // Top
  { char: 'V', fromX: -140, fromY: 140, rotate: 35, delay: 410 },   // Bottom-Left
  { char: 'A', fromX: 130, fromY: -130, rotate: -30, delay: 540 },  // Top-Right
  { char: 'N', fromX: 0, fromY: 140, rotate: 0, delay: 670 },      // Bottom
  { char: 'T', fromX: -140, fromY: 0, rotate: 20, delay: 800 },    // Far Left
  { char: 'A', fromX: 140, fromY: 0, rotate: -20, delay: 930 }     // Far Right
];

export function RyvantaIntroLoader({ onComplete }: { onComplete?: () => void }) {
  const [mounted, setMounted] = useState(false);
  const [stage, setStage] = useState<'sliding' | 'assembled' | 'subtitles' | 'ready_to_enter' | 'entering' | 'done'>('sliding');
  const [progress, setProgress] = useState(0);
  const hasTriggeredLoginSound = useRef(false);

  useEffect(() => {
    // 1. Initial mounting (0s)
    const mountTimer = setTimeout(() => {
      setMounted(true);
    }, 80);

    // 2. Smooth 3-Second Loading Counter Animation (0 to 100% across ~2800ms)
    const startTime = Date.now();
    const duration = 2800; // 2.8s smooth interpolation to 100%

    const progressInterval = setInterval(() => {
      const elapsed = Date.now() - startTime;
      const pct = Math.min(Math.floor((elapsed / duration) * 100), 100);
      setProgress(pct);
      if (pct >= 100) {
        clearInterval(progressInterval);
      }
    }, 40);

    // Phase 2: Assembled at 1.1s
    const assembledTimer = setTimeout(() => {
      setStage('assembled');
    }, 1100);

    // Phase 3: Subtitles reveal at 1.7s
    const subtitlesTimer = setTimeout(() => {
      setStage('subtitles');
    }, 1700);

    // Phase 4: Ready for Login after 3 full seconds (3000ms)
    const readyTimer = setTimeout(() => {
      setStage('ready_to_enter');
    }, 3000);

    return () => {
      clearTimeout(mountTimer);
      clearInterval(progressInterval);
      clearTimeout(assembledTimer);
      clearTimeout(subtitlesTimer);
      clearTimeout(readyTimer);
    };
  }, []);

  function handleLoginToWebsite() {
    if (stage === 'entering' || stage === 'done') return;

    // Play the multi-layered technical sound sequence exclusively upon login
    if (!hasTriggeredLoginSound.current) {
      hasTriggeredLoginSound.current = true;
      playPortalLoginSound();
    }

    setStage('entering');

    setTimeout(() => {
      setStage('done');
      onComplete?.();
    }, 750);
  }

  if (stage === 'done') {
    return null;
  }

  return (
    <div
      className={`fixed inset-0 z-[99999] flex flex-col items-center justify-center bg-[#000000] text-white select-none overflow-hidden transition-all duration-700 ease-out ${
        stage === 'entering' ? 'opacity-0 scale-105 pointer-events-none' : 'opacity-100 scale-100'
      }`}
      aria-label="Loading RYVANTA 26"
    >
      {/* Laser edge beams sliding from border edges */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        {/* Top edge beam */}
        <div
          className={`absolute top-0 left-0 h-[2px] w-full bg-[#0EA5E9] transition-all duration-1000 ease-out ${
            mounted ? 'translate-x-0 opacity-80' : '-translate-x-full opacity-0'
          }`}
        />
        {/* Bottom edge beam */}
        <div
          className={`absolute bottom-0 left-0 h-[2px] w-full bg-[#0EA5E9] transition-all duration-1000 ease-out ${
            mounted ? 'translate-x-0 opacity-80' : 'translate-x-full opacity-0'
          }`}
        />
        {/* Left edge beam */}
        <div
          className={`absolute top-0 left-0 w-[2px] h-full bg-[#CBD5E1] transition-all duration-1000 ease-out ${
            mounted ? 'translate-y-0 opacity-60' : '-translate-y-full opacity-0'
          }`}
        />
        {/* Right edge beam */}
        <div
          className={`absolute top-0 right-0 w-[2px] h-full bg-[#CBD5E1] transition-all duration-1000 ease-out ${
            mounted ? 'translate-y-0 opacity-60' : 'translate-y-full opacity-0'
          }`}
        />

        {/* Ambient Center Glow */}
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 h-96 w-96 rounded-full bg-[#0EA5E9]/15 blur-3xl pointer-events-none" />
      </div>

      {/* Top Organization Pill */}
      <div
        className={`mb-6 flex items-center gap-2 rounded-full border border-slate-800 bg-slate-950/90 px-4 py-1.5 text-xs font-mono font-bold uppercase tracking-widest text-slate-300 shadow-xl transition-all duration-700 ${
          stage === 'subtitles' || stage === 'ready_to_enter' || stage === 'entering'
            ? 'opacity-100 translate-y-0'
            : 'opacity-0 -translate-y-8'
        }`}
      >
        <SparklesIcon className="h-3.5 w-3.5 text-[#0EA5E9] animate-pulse" />
        <span>Jaya Engineering College</span>
      </div>

      {/* ───────────────────────────────────────────────────────────── */}
      {/* MAIN RYVANTA LETTERS CONVERGING FROM EDGES */}
      {/* ───────────────────────────────────────────────────────────── */}
      <div className="relative flex items-center justify-center font-serif text-5xl sm:text-7xl md:text-8xl lg:text-9xl font-black tracking-wider">
        <div className="flex items-center">
          {LETTERS_CONFIG.map((item, index) => {
            const isSlidIn = mounted;
            return (
              <span
                key={index}
                className="inline-block transition-all duration-700 ease-out"
                style={{
                  transform: isSlidIn
                    ? 'translate3d(0, 0, 0) rotate(0deg) scale(1)'
                    : `translate3d(${item.fromX}vw, ${item.fromY}vh, 0) rotate(${item.rotate}deg) scale(0.6)`,
                  opacity: isSlidIn ? 1 : 0,
                  transitionDelay: `${item.delay}ms`,
                  textShadow:
                    stage === 'assembled' || stage === 'subtitles' || stage === 'ready_to_enter'
                      ? '0 0 35px rgba(14, 165, 233, 0.65), 0 0 10px rgba(255, 255, 255, 0.4)'
                      : 'none'
                }}
              >
                <span className="text-[#FFFFFF]">
                  {item.char}
                </span>
              </span>
            );
          })}
        </div>

        {/* '26 Badge exploding into position */}
        <span
          className={`ml-2 sm:ml-3 inline-block font-mono text-3xl sm:text-5xl md:text-6xl font-black transition-all duration-500 ease-out ${
            stage === 'assembled' || stage === 'subtitles' || stage === 'ready_to_enter' || stage === 'entering'
              ? 'opacity-100 scale-100 translate-y-0'
              : 'opacity-0 scale-0 translate-y-8'
          }`}
          style={{
            textShadow: '0 0 25px rgba(14, 165, 233, 0.9)'
          }}
        >
          <span className="text-[#0EA5E9]">
            '26
          </span>
        </span>
      </div>

      {/* Subtitle Line */}
      <p
        className={`mt-4 text-center font-sans text-xs sm:text-sm font-semibold uppercase tracking-[0.25em] text-slate-400 transition-all duration-700 ${
          stage === 'subtitles' || stage === 'ready_to_enter' || stage === 'entering'
            ? 'opacity-100 translate-y-0'
            : 'opacity-0 translate-y-6'
        }`}
      >
        National Level Tech Innovation Challenge
      </p>

      {/* ───────────────────────────────────────────────────────────── */}
      {/* LOGIN TO WEBSITE ACTION (EXTENDED 3-SEC LOADING COMPLETION) */}
      {/* ───────────────────────────────────────────────────────────── */}
      <div className="mt-8 flex flex-col items-center gap-4">
        {stage === 'ready_to_enter' ? (
          <button
            type="button"
            onClick={handleLoginToWebsite}
            autoFocus
            className="group relative inline-flex items-center gap-2.5 rounded-2xl bg-[#0EA5E9] px-8 py-4 text-xs font-mono font-bold uppercase tracking-widest text-[#FFFFFF] shadow-2xl hover:bg-[#0284C7] hover:scale-105 hover:shadow-blue-glow transition-all duration-200 animate-bounce"
          >
            <CpuIcon className="h-4 w-4 text-white animate-spin" />
            <span>LOGIN TO RYVANTA PORTAL</span>
            <ArrowRightIcon className="h-4 w-4 text-white group-hover:translate-x-1 transition-transform" />
          </button>
        ) : (
          /* 3-Second Cyber Progress Indicator Bar */
          <div className="flex flex-col items-center gap-2 w-64 sm:w-80">
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-900 border border-slate-800">
              <div
                className="h-full bg-[#0EA5E9] shadow-blue-glow transition-all duration-100 ease-linear"
                style={{ width: `${progress}%` }}
              />
            </div>
            <div className="flex w-full items-center justify-between font-mono text-[10px] text-slate-500">
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-[#0EA5E9] animate-ping" />
                SYSTEM INITIALIZING
              </span>
              <span className="font-bold text-[#0EA5E9]">{progress}%</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default RyvantaIntroLoader;

// src/components/RyvantaIntroLoader.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const emit = defineEmits(["complete"]);

const mounted = ref(false);
const stage = ref("sliding");
const progress = ref(0);

let progressInterval;

onMounted(() => {
	// 1. Initial mounting (0s)
	setTimeout(() => {
		mounted.value = true;
	}, 80);

	// 2. Smooth Loading Counter
	const startTime = Date.now();
	const duration = 2800;

	progressInterval = setInterval(() => {
		const elapsed = Date.now() - startTime;
		const pct = Math.min(Math.floor((elapsed / duration) * 100), 100);
		progress.value = pct;
		if (pct >= 100) {
			clearInterval(progressInterval);
		}
	}, 40);

	// Phase 2: Assembled
	setTimeout(() => {
		stage.value = "assembled";
	}, 300);

	// Phase 3: Subtitles reveal
	setTimeout(() => {
		stage.value = "subtitles";
	}, 800);

	// Phase 4: Ready to boot sequence (skipped boot sequence straight to done)
	setTimeout(() => {
		handleLoginToWebsite();
	}, 3200);
});

onUnmounted(() => {
	clearInterval(progressInterval);
});

function handleLoginToWebsite() {
	if (stage.value === "entering" || stage.value === "done") return;

	stage.value = "entering";

	setTimeout(() => {
		stage.value = "done";
		emit("complete");
	}, 750);
}
</script>

<template>
	<div
		v-if="stage !== 'done'"
		class="loader-overlay"
		:class="{
			entering: stage === 'entering',
		}"
	>
		<!-- Top Organization Pill -->
		<div
			class="org-pill"
			:class="{
				'org-pill-active': [
					'subtitles',
					'ready_to_enter',
					'entering',
				].includes(stage),
			}"
		>
			<span>Jaya Engineering College</span>
		</div>

		<!-- MAIN RYVANTA LETTERS -->
		<div class="title-container">
			<div class="letters-container">
				<!-- R -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>R</span
				>
				<!-- Y -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>Y</span
				>
				<!-- V -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>V</span
				>
				<!-- A -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>A</span
				>
				<!-- N -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>N</span
				>
				<!-- T -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>T</span
				>
				<!-- A -->
				<span
					class="letter"
					:class="{ 'letter-active': mounted, 'text-glow': true }"
					>A</span
				>
			</div>

			<!-- '26 Badge -->
			<span
				class="year-badge"
				:class="{
					'year-active': [
						'assembled',
						'subtitles',
						'ready_to_enter',
						'entering',
					].includes(stage),
				}"
			>
				'26
			</span>
		</div>

		<!-- Subtitle Line -->
		<p
			class="subtitle"
			:class="{
				'subtitle-active': [
					'subtitles',
					'ready_to_enter',
					'entering',
				].includes(stage),
			}"
		>
			Tech Innovation Challenge
		</p>

		<!-- BOOT SEQUENCE OR PROGRESS BAR -->
		<div class="bottom-actions">
			<div class="progress-container">
				<div class="progress-track">
					<div
						class="progress-bar"
						:style="{ width: progress + '%' }"
					></div>
				</div>
				<div class="progress-text">
					<span class="progress-label">
						[INFO] SYSTEM INITIALIZING
					</span>
					<span class="progress-pct">{{ progress }}%</span>
				</div>
			</div>
		</div>
	</div>
</template>

<style scoped>
.loader-overlay {
	position: fixed;
	inset: 0;
	z-index: 99999;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	background-color: #000000;
	color: #ffffff;
	user-select: none;
	overflow: hidden;
	transition: all 700ms ease-out;
	opacity: 1;
	transform: scale(1);
}
.loader-overlay.entering {
	opacity: 0;
	transform: scale(1.05);
	pointer-events: none;
}
.pointer-events-none {
	pointer-events: none;
}

.ambient-glow {
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%, -50%);
	height: 24rem;
	width: 24rem;
	border-radius: 9999px;
	background-color: rgba(14, 165, 233, 0.15);
	filter: blur(64px);
}

.org-pill {
	margin-bottom: 1.5rem;
	display: flex;
	align-items: center;
	gap: 0.5rem;
	border-radius: 9999px;
	border: 1px solid #1e293b;
	background-color: rgba(2, 6, 23, 0.9);
	padding: 0.375rem 1rem;
	font-size: 0.75rem;
	font-family: var(--font-mono);
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: #cbd5e1;
	box-shadow:
		0 20px 25px -5px rgba(0, 0, 0, 0.1),
		0 10px 10px -5px rgba(0, 0, 0, 0.04);
	transition: all 700ms;
	opacity: 0;
	transform: translateY(-2rem);
}
.org-pill-active {
	opacity: 1;
	transform: translateY(0);
}
.sparkle {
	color: #0ea5e9;
	animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}
@keyframes pulse {
	0%,
	100% {
		opacity: 1;
	}
	50% {
		opacity: 0.5;
	}
}

.title-container {
	position: relative;
	display: flex;
	align-items: center;
	justify-content: center;
	font-family: var(--font-sans);
	font-size: 3rem;
	font-weight: 900;
	letter-spacing: 0.05em;
}
@media (min-width: 640px) {
	.title-container {
		font-size: 4.5rem;
	}
}
@media (min-width: 768px) {
	.title-container {
		font-size: 6rem;
	}
}
@media (min-width: 1024px) {
	.title-container {
		font-size: 8rem;
	}
}

.letters-container {
	display: flex;
	align-items: center;
}
.letter {
	display: inline-block;
	opacity: 0;
	transition: opacity 1000ms ease-in;
}
.letter-active {
	opacity: 1;
}
.text-glow {
	text-shadow:
		0 0 35px rgba(14, 165, 233, 0.65),
		0 0 10px rgba(255, 255, 255, 0.4);
}

.year-badge {
	margin-left: 0.5rem;
	display: inline-block;
	font-family: var(--font-mono);
	font-size: 1.875rem;
	font-weight: 900;
	transition: all 500ms ease-out;
	opacity: 0;
	transform: scale(0) translateY(2rem);
	text-shadow: 0 0 25px rgba(14, 165, 233, 0.9);
	color: #0ea5e9;
}
@media (min-width: 640px) {
	.year-badge {
		font-size: 4rem;
		margin-left: 0.75rem;
	}
}
@media (min-width: 768px) {
	.year-badge {
		font-size: 5.75rem;
	}
}
.year-active {
	opacity: 1;
	transform: scale(1) translateY(0);
}

.subtitle {
	margin-top: 1rem;
	text-align: center;
	font-family: var(--font-sans);
	font-size: 0.75rem;
	font-weight: 600;
	text-transform: uppercase;
	letter-spacing: 0.25em;
	color: #94a3b8;
	transition: all 700ms;
	opacity: 0;
	transform: translateY(1.5rem);
}
@media (min-width: 640px) {
	.subtitle {
		font-size: 0.875rem;
	}
}
.subtitle-active {
	opacity: 1;
	transform: translateY(0);
}

.bottom-actions {
	margin-top: 2rem;
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 1rem;
	height: 6rem; /* fixed height to avoid layout shift */
}

/* Progress bar */
.progress-container {
	width: 16rem;
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 0.5rem;
}
@media (min-width: 640px) {
	.progress-container {
		width: 20rem;
	}
}
.progress-track {
	height: 0.375rem;
	width: 100%;
	overflow: hidden;
	border-radius: 9999px;
	background-color: #0f172a;
	border: 1px solid #1e293b;
}
.progress-bar {
	height: 100%;
	background-color: #0ea5e9;
	box-shadow: 0 0 20px rgba(14, 165, 233, 0.35);
	transition: all 100ms linear;
}
.progress-text {
	display: flex;
	width: 100%;
	align-items: center;
	justify-content: space-between;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	color: #64748b;
}
.progress-label {
	display: flex;
	align-items: center;
	gap: 0.375rem;
}
.ping-dot {
	display: inline-block;
	height: 0.375rem;
	width: 0.375rem;
	border-radius: 9999px;
	background-color: #0ea5e9;
	animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite;
}
@keyframes ping {
	75%,
	100% {
		transform: scale(2);
		opacity: 0;
	}
}
.progress-pct {
	font-weight: 700;
	color: #0ea5e9;
}

/* Boot sequence */
.boot-sequence {
	width: 16rem;
	font-family: var(--font-mono);
	font-size: 0.75rem;
	color: #10b981; /* Hacker green */
	text-align: left;
	display: flex;
	flex-direction: column;
	gap: 0.25rem;
}
@media (min-width: 640px) {
	.boot-sequence {
		width: 20rem;
		font-size: 0.875rem;
	}
}
.boot-line {
	animation: type 0.2s steps(40, end);
	white-space: nowrap;
	overflow: hidden;
}
.boot-cursor {
	display: inline-block;
	animation: blink 1s step-end infinite;
}
@keyframes blink {
	0%,
	100% {
		opacity: 1;
	}
	50% {
		opacity: 0;
	}
}
</style>
