// src/components/StudentPassCard.vue
<script setup>
import {
	PrinterIcon,
	XIcon,
	SparklesIcon,
	CalendarIcon,
	ClockIcon,
} from "lucide-vue-next";
import QrCodeView from "./QrCodeView.vue";

const props = defineProps({
	registration: { type: Object, required: true },
	isModal: { type: Boolean, default: false },
});

const emit = defineEmits(["close"]);

function handlePrint() {
	window.print();
}
</script>

<template>
	<div class="student-pass-container">
		<!-- Action Bar -->
		<div class="action-bar print-hidden">
			<div class="action-bar-left">
				<div class="module-code">TI</div>
				<div>
					<h3 class="pass-title">
						Official Participation Pass &amp; Entry Badge
					</h3>
					<span class="pass-id">ID: {{ registration.id }}</span>
				</div>
			</div>

			<div class="action-bar-right">
				<button type="button" @click="handlePrint" class="print-button">
					<PrinterIcon class="print-icon" />
					<span>Print Pass</span>
				</button>

				<button
					v-if="isModal"
					type="button"
					@click="emit('close')"
					class="close-button"
				>
					<XIcon class="close-icon" />
				</button>
			</div>
		</div>

		<!-- Cyber Blue & Silver Digital Entry Pass Card -->
		<div class="student-pass-root">
			<!-- Decorative Corner Glow -->
			<div class="corner-glow"></div>

			<!-- Header Ribbon -->
			<div class="pass-header">
				<div class="pass-header-info">
					<div class="college-badge">
						<SparklesIcon class="sparkles-icon" />
						<span>Jaya Engineering College · RYVANTA '26 Pass</span>
					</div>
					<h2 class="event-name">{{ registration.eventName }}</h2>
					<p class="institution-name">
						{{ registration.institution }}
					</p>
				</div>

				<!-- Sequential Participation ID Badge -->
				<div class="id-badge">
					<span class="id-label">Participation ID</span>
					<span class="id-value">{{ registration.id }}</span>
					<span class="id-verified">● Verified Admission</span>
				</div>
			</div>

			<!-- Pass Details Grid -->
			<div class="pass-details">
				<div class="details-main">
					<!-- Squad & Leader -->
					<div class="team-leader-grid">
						<div class="detail-box">
							<span class="detail-label">Team Name</span>
							<p class="detail-value">
								{{ registration.teamName }}
							</p>
						</div>

						<div class="detail-box">
							<span class="detail-label">Team Leader</span>
							<p class="detail-value">
								{{
									registration.leaderName ||
									registration.members[0]
								}}
							</p>
						</div>
					</div>

					<!-- Track / Domain -->
					<div class="detail-box highlight-box">
						<span class="detail-label highlight-label"
							>Assigned Problem Domain / Track</span
						>
						<p class="detail-value-mono">
							{{
								registration.track ||
								registration.domain ||
								"General Track"
							}}
						</p>
					</div>

					<!-- Team Members List -->
					<div class="members-box">
						<span class="detail-label block-label">
							Registered Team Members ({{
								registration.members.length
							}}
							Participants)
						</span>
						<div class="members-grid">
							<div
								v-for="(name, i) in registration.members"
								:key="i"
								class="member-item"
							>
								<span class="member-index">{{
									String(i + 1).padStart(2, "0")
								}}</span>
								<span class="member-name">{{ name }}</span>
							</div>
						</div>
					</div>
				</div>

				<!-- QR Code Validation Box -->
				<div class="qr-validation-box">
					<div class="qr-wrapper">
						<QrCodeView
							:value="`JEC-RYVANTA:${registration.id}|TEAM:${registration.teamName}|EVENT:${registration.eventId}`"
							:size="128"
						/>
					</div>
					<span class="qr-label">Gate Scanner QR</span>
					<span class="qr-date">19-09-2026</span>
				</div>
			</div>

			<!-- Footer Notes -->
			<div class="pass-footer">
				<div class="footer-time-info">
					<span class="time-item">
						<CalendarIcon class="time-icon" />
						19 Sep 2026
					</span>
					<span class="time-item">
						<ClockIcon class="time-icon" />
						08:30 AM IST
					</span>
				</div>
				<span class="footer-note"
					>Jaya Engineering College · Carry physical college ID cards
					to campus.</span
				>
			</div>
		</div>
	</div>
</template>

<style scoped>
.student-pass-container {
	display: flex;
	flex-direction: column;
	gap: 1.5rem;
}

/* Action Bar */
.action-bar {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	justify-content: space-between;
	gap: 0.75rem;
	border-bottom: 1px solid var(--border-light);
	padding-bottom: 1rem;
}

@media print {
	.print-hidden {
		display: none !important;
	}
}

.action-bar-left,
.action-bar-right {
	display: flex;
	align-items: center;
	gap: 0.5rem;
}

.module-code {
	display: flex;
	height: 2rem;
	width: 2rem;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-xl);
	background-color: var(--brand-blue);
	color: #ffffff;
	font-family: var(--font-serif, var(--font-sans));
	font-weight: 700;
	font-size: 0.75rem;
}

.pass-title {
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1rem;
	font-weight: 700;
	color: var(--text-primary);
}

.pass-id {
	font-family: var(--font-mono);
	font-size: 0.75rem;
	font-weight: 700;
	color: var(--brand-blue);
}

.print-button {
	display: inline-flex;
	align-items: center;
	gap: 0.375rem;
	border-radius: var(--radius-xl);
	border: 1px solid var(--brand-blue);
	background-color: var(--bg-primary);
	padding: 0.5rem 1rem;
	font-size: 0.75rem;
	font-weight: 600;
	color: var(--text-primary);
	box-shadow: var(--shadow-sm);
	transition: background-color 0.2s ease;
}

.print-button:hover {
	background-color: var(--bg-secondary);
}

.print-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--brand-blue);
}

.close-button {
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 0.5rem;
	color: var(--text-muted);
	transition: color 0.2s ease;
}

.close-button:hover {
	color: var(--text-primary);
}

.close-icon {
	width: 1rem;
	height: 1rem;
}

/* Card Root */
.student-pass-root {
	position: relative;
	overflow: hidden;
	border-radius: var(--radius-3xl);
	border: 2px solid var(--brand-blue);
	background-color: var(--bg-primary);
	padding: 1.5rem;
	box-shadow: var(--shadow-luxury-lg);
	color: var(--text-primary);
}

@media (min-width: 640px) {
	.student-pass-root {
		padding: 2rem;
	}
}

.corner-glow {
	position: absolute;
	top: -3rem;
	right: -3rem;
	height: 8rem;
	width: 8rem;
	border-radius: 50%;
	background-color: rgba(14, 165, 233, 0.1);
	filter: blur(1rem);
	pointer-events: none;
}

/* Pass Header */
.pass-header {
	display: flex;
	flex-direction: column;
	gap: 1rem;
	border-bottom: 2px solid var(--border-light);
	padding-bottom: 1.5rem;
}

@media (min-width: 640px) {
	.pass-header {
		flex-direction: row;
		align-items: center;
		justify-content: space-between;
	}
}

.college-badge {
	display: inline-flex;
	align-items: center;
	gap: 0.5rem;
	border-radius: var(--radius-full);
	border: 1px solid var(--brand-blue);
	background-color: var(--bg-secondary);
	padding: 0.25rem 0.875rem;
	font-family: var(--font-mono);
	font-size: 0.75rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--brand-blue-hover);
}

.sparkles-icon {
	width: 0.75rem;
	height: 0.75rem;
	color: var(--brand-blue);
}

.event-name {
	margin-top: 0.75rem;
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1.5rem;
	font-weight: 900;
	color: var(--text-primary);
}

@media (min-width: 640px) {
	.event-name {
		font-size: 1.875rem;
	}
}

.institution-name {
	margin-top: 0.25rem;
	font-size: 0.75rem;
	color: var(--text-dark);
}

.id-badge {
	border-radius: var(--radius-2xl);
	border: 2px solid var(--brand-blue);
	background-color: var(--bg-secondary);
	padding: 1rem;
	text-align: center;
	box-shadow: var(--shadow-sm);
}

@media (min-width: 640px) {
	.id-badge {
		text-align: right;
	}
}

.id-label {
	display: block;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--text-muted);
}

.id-value {
	font-family: var(--font-mono);
	font-size: 1.5rem;
	font-weight: 900;
	letter-spacing: 0.05em;
	color: var(--text-primary);
}

@media (min-width: 640px) {
	.id-value {
		font-size: 1.875rem;
	}
}

.id-verified {
	margin-top: 0.25rem;
	display: block;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	color: var(--brand-blue-hover);
}

/* Pass Details */
.pass-details {
	margin-top: 1.5rem;
	display: grid;
	gap: 1.5rem;
	align-items: flex-start;
}

@media (min-width: 640px) {
	.pass-details {
		grid-template-columns: minmax(0, 1fr) 160px;
	}
}

.details-main {
	display: flex;
	flex-direction: column;
	gap: 1rem;
}

.team-leader-grid {
	display: grid;
	gap: 1rem;
}

@media (min-width: 640px) {
	.team-leader-grid {
		grid-template-columns: repeat(2, 1fr);
	}
}

.detail-box {
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 0.875rem;
}

.detail-label {
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--text-muted);
}

.detail-value {
	margin-top: 0.125rem;
	font-family: var(--font-serif, var(--font-sans));
	font-size: 1rem;
	font-weight: 700;
	color: var(--text-primary);
}

.highlight-box {
	border-color: rgba(14, 165, 233, 0.4);
}

.highlight-label {
	color: var(--brand-blue-hover);
}

.detail-value-mono {
	margin-top: 0.125rem;
	font-family: var(--font-mono);
	font-size: 0.875rem;
	font-weight: 700;
	color: var(--text-primary);
}

.members-box {
	border-radius: var(--radius-xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 1rem;
}

.block-label {
	display: block;
	margin-bottom: 0.5rem;
}

.members-grid {
	display: grid;
	gap: 0.5rem;
	font-size: 0.75rem;
}

@media (min-width: 640px) {
	.members-grid {
		grid-template-columns: repeat(2, 1fr);
	}
}

.member-item {
	display: flex;
	align-items: center;
	gap: 0.5rem;
	border-radius: var(--radius-lg);
	background-color: var(--bg-primary);
	border: 1px solid var(--border-light);
	padding: 0.5rem;
}

.member-index {
	display: flex;
	height: 1.25rem;
	width: 1.25rem;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-sm);
	background-color: var(--bg-secondary);
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	color: var(--brand-blue);
}

.member-name {
	font-weight: 500;
	color: var(--text-primary);
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}

/* QR Code Validation Box */
.qr-validation-box {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	border-radius: var(--radius-2xl);
	border: 1px solid var(--border-light);
	background-color: var(--bg-secondary);
	padding: 1rem;
	text-align: center;
}

.qr-wrapper {
	border-radius: var(--radius-xl);
	border: 1px solid var(--brand-blue);
	background-color: var(--bg-primary);
	padding: 0.625rem;
	box-shadow: var(--shadow-sm);
}

.qr-label {
	margin-top: 0.5rem;
	font-family: var(--font-mono);
	font-size: 0.5625rem;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: var(--text-muted);
}

.qr-date {
	margin-top: 0.125rem;
	font-family: var(--font-mono);
	font-size: 0.625rem;
	font-weight: 700;
	color: var(--text-primary);
}

/* Footer Notes */
.pass-footer {
	margin-top: 1.5rem;
	border-top: 2px solid var(--border-light);
	padding-top: 1rem;
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	justify-content: space-between;
	gap: 1rem;
	font-family: var(--font-mono);
	font-size: 0.75rem;
	color: var(--text-muted);
}

.footer-time-info {
	display: flex;
	align-items: center;
	gap: 1rem;
}

.time-item {
	display: inline-flex;
	align-items: center;
	gap: 0.375rem;
	color: var(--text-primary);
	font-weight: 600;
}

.time-icon {
	width: 0.875rem;
	height: 0.875rem;
	color: var(--brand-blue);
}

.footer-note {
	/* optional styles */
}
</style>

// src/components/StudentPassCard.tsx
import React, { useRef } from 'react';
import {
  CheckCircle2Icon,
  DownloadIcon,
  PrinterIcon,
  ShieldCheckIcon,
  UsersIcon,
  MapPinIcon,
  CalendarIcon,
  ClockIcon,
  Share2Icon,
  XIcon,
  SparklesIcon,
  BuildingIcon
} from 'lucide-react';
import type { Registration } from '../types/registration';
import { QrCodeView } from './QrCodeView';

interface StudentPassCardProps {
  registration: Registration;
  onClose?: () => void;
  isModal?: boolean;
}

export function StudentPassCard({
  registration,
  onClose,
  isModal = false
}: StudentPassCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);

  function handlePrint() {
    window.print();
  }

  return (
    <div className="space-y-6">
      {/* Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E2E8F0] pb-4 print:hidden">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#0EA5E9] text-white font-serif font-bold text-xs">
            TI
          </div>
          <div>
            <h3 className="font-serif text-base font-bold text-[#000000]">
              Official Participation Pass &amp; Entry Badge
            </h3>
            <span className="font-mono text-xs text-[#0EA5E9] font-bold">
              ID: {registration.id}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 rounded-xl border border-[#0EA5E9] bg-[#FFFFFF] px-4 py-2 text-xs font-semibold text-[#000000] hover:bg-[#F8FAFC] transition-colors shadow-sm"
          >
            <PrinterIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
            <span>Print Pass</span>
          </button>

          {isModal && onClose && (
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-2 text-[#64748B] hover:text-[#000000]"
            >
              <XIcon className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      {/* Cyber Blue & Silver Digital Entry Pass Card */}
      <div
        ref={cardRef}
        className="student-pass-root relative overflow-hidden rounded-3xl border-2 border-[#0EA5E9] bg-[#FFFFFF] p-6 sm:p-8 shadow-luxury-lg text-[#000000]"
      >
        {/* Decorative Corner Glow */}
        <div className="absolute -top-12 -right-12 h-32 w-32 rounded-full bg-sky-500/10 blur-xl pointer-events-none" />

        {/* Header Ribbon */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b-2 border-[#E2E8F0] pb-6">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-[#0EA5E9] bg-[#F8FAFC] px-3.5 py-1 text-xs font-mono font-bold uppercase tracking-widest text-[#0284C7]">
              <SparklesIcon className="h-3 w-3 text-[#0EA5E9]" />
              <span>Jaya Engineering College · RYVANTA '26 Pass</span>
            </div>
            <h2 className="mt-3 font-serif text-2xl sm:text-3xl font-black text-[#000000]">
              {registration.eventName}
            </h2>
            <p className="text-xs text-[#475569] mt-1">{registration.institution}</p>
          </div>

          {/* Sequential Participation ID Badge */}
          <div className="rounded-2xl border-2 border-[#0EA5E9] bg-[#F8FAFC] p-4 text-center sm:text-right shadow-sm">
            <span className="block font-mono text-[10px] font-bold uppercase tracking-widest text-[#64748B]">
              Participation ID
            </span>
            <span className="font-mono text-2xl sm:text-3xl font-black text-[#000000] tracking-wider">
              {registration.id}
            </span>
            <span className="mt-1 block font-mono text-[10px] text-[#0284C7] font-bold uppercase">
              ● Verified Admission
            </span>
          </div>
        </div>

        {/* Pass Details Grid */}
        <div className="mt-6 grid gap-6 sm:grid-cols-[minmax(0,1fr)_160px] items-start">
          <div className="space-y-4">
            {/* Squad & Leader */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-3.5">
                <span className="font-mono text-[10px] uppercase font-bold tracking-widest text-[#64748B]">
                  Team Name
                </span>
                <p className="font-serif text-base font-bold text-[#000000] mt-0.5">
                  {registration.teamName}
                </p>
              </div>

              <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-3.5">
                <span className="font-mono text-[10px] uppercase font-bold tracking-widest text-[#64748B]">
                  Team Leader
                </span>
                <p className="font-serif text-base font-bold text-[#000000] mt-0.5">
                  {registration.leaderName || registration.members[0]}
                </p>
              </div>
            </div>

            {/* Track / Domain */}
            <div className="rounded-xl border border-[#0EA5E9]/40 bg-[#F8FAFC] p-3.5">
              <span className="font-mono text-[10px] uppercase font-bold tracking-widest text-[#0284C7]">
                Assigned Problem Domain / Track
              </span>
              <p className="font-mono text-sm font-bold text-[#000000] mt-0.5">
                {registration.track || registration.domain || 'General Track'}
              </p>
            </div>

            {/* Team Members List */}
            <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-4">
              <span className="font-mono text-[10px] uppercase font-bold tracking-widest text-[#64748B] block mb-2">
                Registered Team Members ({registration.members.length} Participants)
              </span>
              <div className="grid gap-2 sm:grid-cols-2 text-xs">
                {registration.members.map((name, i) => (
                  <div key={i} className="flex items-center gap-2 rounded-lg bg-[#FFFFFF] border border-[#E2E8F0] p-2">
                    <span className="flex h-5 w-5 items-center justify-center rounded bg-[#F8FAFC] font-mono text-[10px] font-bold text-[#0EA5E9]">
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <span className="font-medium text-[#000000] truncate">{name}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* QR Code Validation Box */}
          <div className="flex flex-col items-center justify-center rounded-2xl border border-[#E2E8F0] bg-[#F8FAFC] p-4 text-center">
            <div className="rounded-xl border border-[#0EA5E9] bg-[#FFFFFF] p-2.5 shadow-sm">
              <QrCodeView
                value={`JEC-RYVANTA:${registration.id}|TEAM:${registration.teamName}|EVENT:${registration.eventId}`}
                size={128}
              />
            </div>
            <span className="mt-2 font-mono text-[9px] font-bold uppercase tracking-wider text-[#64748B]">
              Gate Scanner QR
            </span>
            <span className="font-mono text-[10px] text-[#000000] font-bold mt-0.5">
              19-09-2026
            </span>
          </div>
        </div>

        {/* Footer Notes */}
        <div className="mt-6 border-t-2 border-[#E2E8F0] pt-4 flex flex-wrap items-center justify-between gap-4 text-xs font-mono text-[#64748B]">
          <div className="flex items-center gap-4">
            <span className="inline-flex items-center gap-1.5 text-[#000000] font-semibold">
              <CalendarIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
              19 Sep 2026
            </span>
            <span className="inline-flex items-center gap-1.5 text-[#000000] font-semibold">
              <ClockIcon className="h-3.5 w-3.5 text-[#0EA5E9]" />
              08:30 AM IST
            </span>
          </div>
          <span>Jaya Engineering College · Carry physical college ID cards to campus.</span>
        </div>
      </div>
    </div>
  );
}
